"""
Orchestrator - Workflow executor ONLY (no decision-making)
Executes actions generated by Intelligence Engine

Requirements: 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 21.1, 21.2, 31.2, 31.3
"""

import atexit
import logging
import os
import time

from config.constants import (
    DEFAULT_AGGRESSIVENESS,
    HARD_TIMEOUT_SECONDS,
    LLM_AGENT_MODEL,
)
from database.repositories.engagement_repository import EngagementRepository
from database.repositories.finding_repository import (
    FindingRepository,
)
from database.repositories.rate_limit_repository import RateLimitRepository
from llm_client import LLMClient
from mcp_server import get_mcp_server
from parsers.normalizer import FindingNormalizer
from parsers.parser import Parser
from pipeline_router import execute_recon_pipeline, execute_scan_pipeline
from streaming import (
    StreamingFindingEmitter,
    emit_thinking,
    emit_tool_complete,
    emit_tool_start,
    get_stream_manager,
)
from tasks.utils import load_recon_context, save_recon_context
from tools.llm_payload_generator import LLMPayloadGenerator
from tools.tool_runner import ToolRunner
from tracing import (
    ExecutionSpan,
    StructuredLogger,
    TracingManager,
    get_trace_id,
)
from utils.logging_utils import ScanLogger
from websocket_events import get_websocket_publisher

from .repo_scan import execute_repo_scan

logger = logging.getLogger(__name__)


class EngagementTimeoutError(Exception):
    """Raised when engagement exceeds hard timeout"""

    pass


class Orchestrator:
    """
    Workflow execution engine.
    Executes actions generated by Intelligence Engine without making decisions.
    """

    def __init__(self, engagement_id: str, trace_id: str = None):
        self.engagement_id = engagement_id
        self.start_time = time.time()
        self.trace_id = trace_id
        self.bug_bounty_mode = False

        db_conn = os.getenv("DATABASE_URL")
        self.tracing_manager = TracingManager(db_conn)
        self.logger = StructuredLogger(db_conn)
        self.span_recorder = ExecutionSpan(db_conn)
        self.ws_publisher = get_websocket_publisher()
        self.tool_runner = ToolRunner(
            connection_string=db_conn, engagement_id=self.engagement_id
        )
        atexit.register(self._cleanup)
        self.parser = Parser(connection_string=db_conn)
        self.normalizer = FindingNormalizer()
        self.finding_repo = FindingRepository(db_conn) if db_conn else None
        self.engagement_repo = EngagementRepository(db_conn) if db_conn else None
        self.rate_limit_repo = RateLimitRepository(db_conn) if db_conn else None

        self.llm_client = None
        self.llm_payload_generator = None
        try:
            redis_url = os.getenv("REDIS_URL", "redis://localhost:6379")

            # M-v5-01: Resolve user_email from engagement_id for tenant-scoped API key lookup
            user_email = None
            try:
                from database.connection import db_cursor

                with db_cursor() as cursor:
                    cursor.execute(
                        """SELECT u.email FROM engagements e
                           JOIN users u ON e.created_by = u.id
                           WHERE e.id = %s""",
                        (engagement_id,),
                    )
                    row = cursor.fetchone()
                    if row:
                        user_email = row[0]
            except Exception:
                logger.debug(
                    "Could not resolve user_email for engagement %s", engagement_id
                )

            self.llm_client = LLMClient(redis_url=redis_url, user_email=user_email)
            if self.llm_client.is_available():
                from config.constants import LLM_PAYLOAD_GENERATION_MODEL
                from llm_client import load_llm_setting

                llm_payload_enabled = (
                    load_llm_setting("llm_payload_generation_enabled", "true") == "true"
                )
                if llm_payload_enabled:
                    self.llm_payload_generator = LLMPayloadGenerator(
                        llm_client=self.llm_client,
                        model=LLM_PAYLOAD_GENERATION_MODEL,
                    )
                    logger.info("LLM payload generator initialized")
        except Exception as e:
            logger.warning("LLM components not available (graceful degradation): %s", e)

        self.mcp = get_mcp_server()
        self.stream = get_stream_manager()
        self._register_mcp_tools()

    def _cleanup(self):
        """Clean up temporary sandbox directory created by ToolRunner"""
        try:
            self.tool_runner.cleanup()
        except Exception:
            logger.exception("Error during tool runner cleanup")

    def _register_mcp_tools(self):
        """
        Register tools with the MCP server.

        Uses MCPToolBridge to register tools that route through ToolRunner,
        providing sandboxing, circuit breakers, and metrics recording.
        Falls back to direct registration via build_mcp_tool_definitions().
        """
        try:
            from tools.mcp_bridge import MCPToolBridge

            self.mcp_bridge = MCPToolBridge(
                tool_runner=self.tool_runner,
                engagement_id=self.engagement_id,
            )
        except Exception as e:
            logger.warning(
                "MCPToolBridge failed to initialize (falling back to direct registration): %s",
                e,
            )
            self.mcp_bridge = None
            from tool_definitions import build_mcp_tool_definitions

            for tool in build_mcp_tool_definitions():
                self.mcp.register_tool(tool)

    def mcp_run(self, tool: str, arguments: dict = None) -> dict:
        """
        Run a tool via MCP, routing through MCPToolBridge when available.

        When MCPToolBridge is initialized, calls route through ToolRunner
        for sandboxing, circuit breakers, and metrics. Otherwise falls back
        to the direct MCP server call_tool().
        """
        emit_tool_start(self.engagement_id, tool, list((arguments or {}).keys()))
        if hasattr(self, "mcp_bridge") and self.mcp_bridge is not None:
            result = self.mcp_bridge.call_via_mcp(tool, arguments or {})
        else:
            result = self.mcp.call_tool(tool, arguments)
        success = not result.get("isError", False)
        emit_tool_complete(
            self.engagement_id,
            tool,
            success,
            result.get("meta", {}).get("duration_ms", 0),
        )
        return result

    def _load_priority_vuln_classes(self) -> list[str]:
        """Load priority_vuln_classes from the engagement record."""
        from orchestrator_pkg.engagement import EngagementService

        return EngagementService.load_priority_vuln_classes(self.engagement_id)

    def run(self, job: dict) -> dict:
        if self.start_time is None:
            self.start_time = time.time()
        self._check_timeout()
        job_type = job.get("type")
        with self.span_recorder.span(ExecutionSpan.SPAN_ORCHESTRATOR_STEP):
            self.logger.log(
                "orchestrator_step",
                "Routing job: %s",
                job_type,
                {"job_type": job_type, "engagement_id": self.engagement_id},
            )
            if job_type == "recon":
                return self.run_recon(job)
            elif job_type == "scan":
                return self.run_scan(job)
            elif job_type == "analyze":
                return self.run_analysis(job)
            elif job_type == "report":
                return self.run_reporting(job)
            elif job_type == "repo_scan":
                return self.run_repo_scan(job)
            else:
                raise ValueError(f"Unknown job type: {job_type}")

    def run_recon(self, job: dict) -> dict:
        slog = ScanLogger("orchestrator", engagement_id=self.engagement_id)
        slog.tool_start("orchestrator.run_recon", ["target"])
        self._check_timeout()
        self.bug_bounty_mode = bool(job.get("bug_bounty_mode", False))
        target = job.get("target")
        if not target:
            targets_list = job.get("targets", [])
            target = targets_list[0] if targets_list else None
        if not target:
            logger.warning(
                "run_recon called with no target for engagement %s, skipping",
                self.engagement_id,
            )
            # Also transition the DB state, not just the websocket
            try:
                from state_machine import EngagementStateMachine

                sm = EngagementStateMachine(
                    self.engagement_id, current_state=self._get_scan_state()
                )
                sm.transition("failed", "No target URL configured for engagement")
            except Exception:
                logger.warning(
                    "Failed to transition engagement state for no-target case"
                )
            self.ws_publisher.publish_state_transition(
                engagement_id=self.engagement_id,
                from_state=self._get_scan_state(),
                to_state="failed",
                reason="Recon skipped — no target URL configured",
            )
            return {
                "phase": "recon",
                "status": "failed",
                "findings_count": 0,
                "next_state": "failed",
                "trace_id": get_trace_id(),
                "error": "No target URL configured for engagement",
            }

        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id, job_type="recon", target=target
        )
        self.logger.log_job_started(
            job_type="recon", engagement_id=self.engagement_id, target=target
        )
        emit_thinking(self.engagement_id, f"Starting reconnaissance against {target}")
        # State change published via state machine _ws_publisher in transition()
        logger.debug("Recon starting for engagement %s", self.engagement_id)

        aggressiveness = job.get("aggressiveness", DEFAULT_AGGRESSIVENESS)
        findings, recon_context = execute_recon_pipeline(
            self, target, job.get("budget", {}), aggressiveness
        )
        slog.tool_complete(
            "orchestrator.run_recon", success=True, findings=len(findings)
        )

        findings_count = len(findings)
        failed_saves = self._save_findings(findings)
        if failed_saves > 0:
            slog.warning(
                "%d/%d recon findings failed to save", failed_saves, findings_count
            )
            if failed_saves == findings_count:
                raise RuntimeError(
                    f"All {findings_count} recon findings failed to save — aborting phase"
                )

        if recon_context:
            try:
                save_recon_context(self.engagement_id, recon_context)
            except Exception as e:
                logger.warning("Failed to save recon context to Redis: %s", e)

        slog.info("Recon complete: %d findings", findings_count)
        return {
            "phase": "recon",
            "status": "completed",
            "findings_count": findings_count,
            "next_state": "scanning",
            "recon_context": recon_context.to_dict()
            if hasattr(recon_context, "to_dict")
            else recon_context,
            "trace_id": get_trace_id(),
        }

    def _normalize_finding(self, raw_finding: dict, tool: str) -> dict | None:
        from orchestrator_pkg.normalizer_utils import normalize_finding

        return normalize_finding(self.normalizer, raw_finding, tool)

    @staticmethod
    def _classify_finding_type(finding_type: str) -> dict[str, str | None]:
        from parsers.normalizer import FindingNormalizer

        return FindingNormalizer.TYPE_CLASSIFICATION_MAP.get(
            finding_type, {"owasp": "N/A", "cwe": "N/A"}
        )

    def _save_findings(self, findings: list[dict]) -> int:
        """Save findings to the database.

        Delegates to FindingPersistenceService.

        Returns:
            Number of findings that failed to save. 0 means all succeeded.
            Callers should check this and abort the phase if too many fail.
        """
        from orchestrator_pkg.persistence import FindingPersistenceService

        svc = FindingPersistenceService(
            engagement_id=self.engagement_id,
            finding_repo=self.finding_repo,
            bug_bounty_mode=self.bug_bounty_mode,
            classify_finding_type_fn=self._classify_finding_type,
            get_org_id_fn=self._get_org_id,
        )
        return svc.save(findings)

    def run_scan_with_agent(
        self,
        targets,
        recon_context,
        aggressiveness=DEFAULT_AGGRESSIVENESS,
        authorized_scope=None,
        auth_config=None,
        dual_auth_config=None,
        bug_bounty_mode=False,
        budget=None,
    ):
        from agent import AgentResult, create_phase_agent
        from database.repositories.agent_decision_repository import (
            AgentDecisionRepository,
        )
        from feature_flags import is_enabled as _ff_enabled
        from runtime import ExecutionEngine
        from tools.scope_validator import ScopeValidator, ScopeViolationError

        db_conn = os.getenv("DATABASE_URL")
        decision_repo = AgentDecisionRepository(db_conn) if db_conn else None
        all_findings = []
        per_target_tools = []
        budget = budget or {}

        for target in targets:
            try:
                agent = create_phase_agent(
                    phase="scan",
                    tool_runner=self.tool_runner,
                    engagement_id=self.engagement_id,
                    llm_client=self.llm_client,
                    decision_repo=decision_repo,
                    mode="bugbounty" if bug_bounty_mode else None,
                )

                # Phase 3/4: Use ExecutionEngine with mandatory scope validation
                # middleware when CLEAN_ORCHESTRATOR is enabled.
                if _ff_enabled("CLEAN_ORCHESTRATOR", default=False):
                    # ExecutionEngine auto-registers scope validation as mandatory
                    # middleware when scope_validator is provided. No manual
                    # middleware registration needed.
                    _exec_engine = ExecutionEngine(
                        tool_runner=self.tool_runner,
                        scope_validator=ScopeValidator(
                            self.engagement_id, authorized_scope
                        )
                        if authorized_scope
                        else None,
                    )
                    self._execution_engine = _exec_engine

                    # Wrap agent registry.call to run scope middleware before dispatch.
                    # The middleware validates targets; actual tool dispatch still
                    # goes through the agent's registered tool functions.
                    _original_call = agent.registry.call

                    def _scoped_dispatch(
                        name, _ee=_exec_engine, _orig=_original_call, **kwargs
                    ):
                        # Run middleware chain for scope validation
                        args = []
                        for fn in _ee._middleware:
                            result = fn(name, args, kwargs)
                            if result is None:
                                from agent import AgentResult

                                return AgentResult(
                                    tool=name,
                                    success=False,
                                    error="Blocked by scope validation",
                                )
                            if isinstance(result, tuple) and len(result) == 3:
                                name, args, kwargs = result
                        return _orig(name, **kwargs)

                    agent.registry.call = _scoped_dispatch
                else:
                    # Legacy scope validation wrapper (backward compatible)
                    if authorized_scope:
                        _scope_validator = ScopeValidator(
                            self.engagement_id, authorized_scope
                        )
                        _original_call = agent.registry.call

                        def scoped_call(
                            name,
                            _scope_validator=_scope_validator,
                            _original_call=_original_call,
                            **kwargs,
                        ):
                            _target_params = [
                                "target",
                                "url",
                                "host",
                                "hostname",
                                "domain",
                                "endpoint",
                            ]
                            for _param in _target_params:
                                tgt = kwargs.get(_param, "")
                                if tgt:
                                    try:
                                        _scope_validator.validate_target(tgt)
                                    except ScopeViolationError as e:
                                        logger.warning(
                                            "Scope violation blocked (%s): %s",
                                            _param,
                                            e,
                                        )
                                        emit_thinking(
                                            self.engagement_id,
                                            f"Blocked: {tgt} is out of scope",
                                        )
                                        return AgentResult(
                                            tool=name,
                                            success=False,
                                            error=f"Scope violation: {e}",
                                        )
                            return _original_call(name, **kwargs)

                        agent.registry.call = scoped_call

                emit_thinking(
                    self.engagement_id,
                    f"LLM agent selecting scan tools for {target}...",
                )
                results = agent.run(
                    task=f"scan: {target}",
                    initial_context={"recon_context": recon_context, "target": target},
                    recon_context=recon_context,
                )

                agent_ran_tools = {r.tool for r in results if r.success}
                logger.info("Agent ran tools for %s: %s", target, agent_ran_tools)
                per_target_tools.append(agent_ran_tools)

                for r in results:
                    if r.success and r.output:
                        parsed = self.parser.parse(r.tool, r.output)
                        for p in parsed:
                            norm = self._normalize_finding(p, r.tool)
                            if norm:
                                all_findings.append(norm)
            except Exception as e:
                logger.warning(
                    "Agent scan failed for %s: %s — falling back to deterministic",
                    target,
                    e,
                    exc_info=True,
                )
                per_target_tools.append(set())
                fallback = execute_scan_pipeline(
                    self,
                    [target],
                    budget,
                    aggressiveness,
                    auth_config,
                    dual_auth_config=dual_auth_config,
                    tech_stack=recon_context.tech_stack if recon_context else None,
                )
                for f in fallback:
                    norm = self._normalize_finding(f, f.get("source_tool", "fallback"))
                    if norm:
                        all_findings.append(norm)

        union_set = set.union(*per_target_tools) if per_target_tools else set()
        from feature_flags import is_enabled as _ff_enabled

        if _ff_enabled("ENGAGEMENT_STATE", default=False) and hasattr(self, "state"):
            self.state.record_tried_tools(union_set)
        # Always store tried tools on the orchestrator instance so
        # _run_scan_with_fallback can use them for safety-net filtering
        # even when ENGAGEMENT_STATE feature flag is disabled.
        self._agent_tried_tools = union_set

        return all_findings

    def run_scan(self, job: dict) -> dict:
        slog = ScanLogger("orchestrator", engagement_id=self.engagement_id)
        slog.tool_start(
            "orchestrator.run_scan", [f"{len(job.get('targets', []))} targets"]
        )
        self._check_timeout()
        targets = job.get("targets", [])
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id, job_type="scan", target=str(targets)
        )
        self.logger.log_job_started(
            job_type="scan", engagement_id=self.engagement_id, target=str(targets)
        )

        from orchestrator_pkg.custom_rules import CustomRulesService

        CustomRulesService.publish(
            engagement_id=self.engagement_id,
            targets=targets,
            ws_publisher=self.ws_publisher,
        )

        scan_aggressiveness = job.get("aggressiveness", DEFAULT_AGGRESSIVENESS)
        recon_context = job.get("recon_context") or load_recon_context(
            self.engagement_id
        )
        auth_config = job.get("auth_config", {})
        dual_auth_config = job.get(
            "dual_auth_config"
        )  # None = not provided; {} = explicitly empty
        bug_bounty_mode = job.get("bug_bounty_mode", False)

        # Respect user-configured scan mode and agent mode.
        # Priority: explicit scan_mode > agent_mode flag > default (agent-first with fallback)
        scan_mode = job.get("scan_mode", "agent")
        agent_mode = job.get("agent_mode", True)

        from feature_flags import is_enabled as _ff_enabled

        if _ff_enabled("ENGAGEMENT_STATE", default=False) and hasattr(self, "state"):
            self.state.bug_bounty_mode = bool(bug_bounty_mode)
            self.state.agent_mode_enabled = bool(agent_mode)

        budget = job.get("budget", {})
        if not agent_mode or scan_mode == "deterministic":
            # User explicitly disabled agent or requested deterministic-only scan.
            # Skip LLM agent entirely — run full deterministic scan without fallback.
            logger.info(
                "Orchestrator running deterministic-only scan for engagement %s (agent_mode=%s, scan_mode=%s)",
                self.engagement_id,
                agent_mode,
                scan_mode,
            )
            tech_stack = recon_context.tech_stack if recon_context else None
            findings = execute_scan_pipeline(
                self,
                targets,
                budget,
                scan_aggressiveness,
                auth_config,
                dual_auth_config=dual_auth_config,
                tech_stack=tech_stack,
                recon_context=recon_context,
            )
        else:
            # Agent-first scan with deterministic safety-net fallback.
            logger.info(
                "Orchestrator running agent-first scan for engagement %s (scan_mode=%s)",
                self.engagement_id,
                scan_mode,
            )
            findings = self._run_scan_with_fallback(
                targets,
                recon_context,
                budget,
                scan_aggressiveness,
                auth_config,
                bug_bounty_mode,
                dual_auth_config=dual_auth_config,
            )

        self._maybe_run_browser_scanner(targets, recon_context, findings)

        slog.info("Scan complete — %d total findings", len(findings))
        findings_count = len(findings)
        failed_saves = self._save_findings(findings)
        if failed_saves > 0:
            slog.warning(
                "%d/%d scan findings failed to save", failed_saves, findings_count
            )
            if failed_saves == findings_count:
                raise RuntimeError(
                    f"All {findings_count} scan findings failed to save — aborting phase"
                )

        slog.tool_complete(
            "orchestrator.run_scan", success=True, findings=findings_count
        )
        return {
            "phase": "scan",
            "status": "completed",
            "findings_count": findings_count,
            "next_state": "analyzing",
            "trace_id": get_trace_id(),
        }

    def _run_scan_with_fallback(
        self,
        targets: list[str],
        recon_context,
        budget: dict,
        aggressiveness: str,
        auth_config: dict,
        bug_bounty_mode: bool = False,
        dual_auth_config: dict | None = None,
    ) -> list[dict]:
        """
        Agent-first scan with deterministic fallback.

        Phase 3: The orchestrator no longer selects between agent and deterministic
        modes. It always tries the agent first. If the agent succeeds, a safety-net
        deterministic pass runs with tools the agent already tried skipped. If the
        agent fails entirely, a full deterministic scan runs as fallback.

        Tried-tool tracking: Always extracts agent-tried tools from the
        EngagementState (when available) OR from the scan result metadata
        returned by run_scan_with_agent to prevent the safety net from
        duplicating findings the agent already produced.
        """
        slog = ScanLogger("orchestrator", engagement_id=self.engagement_id)
        slog.phase_header("SCAN WITH FALLBACK", targets=f"{len(targets)} target(s)")
        emit_thinking(self.engagement_id, "Running agent-driven scan...")
        try:
            findings = self.run_scan_with_agent(
                targets,
                recon_context,
                aggressiveness,
                auth_config=auth_config,
                dual_auth_config=dual_auth_config,
                bug_bounty_mode=bug_bounty_mode,
                budget=budget,
            )
            from feature_flags import is_enabled as _ff_enabled

            agent_tried: set[str] = set()
            # Prefer EngagementState when available (feature-flagged)
            if _ff_enabled("ENGAGEMENT_STATE", default=False) and hasattr(
                self, "state"
            ):
                agent_tried = self.state.tried_tools
            # Always extract tried tools from per_target_tools via the agent
            # result metadata if possible. This ensures the safety net skips
            # tools the agent already ran even when ENGAGEMENT_STATE is off.
            if hasattr(self, "_agent_tried_tools") and self._agent_tried_tools:
                agent_tried = agent_tried | self._agent_tried_tools
            logger.info(
                "Agent scan complete — safety net skipping agent tools: %s", agent_tried
            )
            tech_stack = recon_context.tech_stack if recon_context else None
            deterministic_findings = execute_scan_pipeline(
                self,
                targets,
                budget,
                aggressiveness,
                auth_config,
                dual_auth_config=dual_auth_config,
                tech_stack=tech_stack,
                skip_tools=agent_tried,
                recon_context=recon_context,
            )
            # Normalize deterministic findings before extending — they are raw
            # dicts from execute_scan_pipeline, not normalized via _normalize_finding().
            # Without this, downstream persistence/storage receives findings with
            # missing source_tool, malformed evidence, etc.
            for f in deterministic_findings:
                norm = self._normalize_finding(f, f.get("source_tool", "fallback"))
                if norm:
                    findings.append(norm)
            slog.tool_complete(
                "scan_with_fallback", success=True, findings=len(findings)
            )
            return findings
        except Exception as agent_err:
            slog.warning(
                "Agent scan failed for engagement %s, falling back to full deterministic: %s",
                self.engagement_id,
                agent_err,
            )
            # Full deterministic fallback via DeterministicRuntime
            from runtime import DeterministicRuntime

            dr = DeterministicRuntime(
                self,
                execution_engine=self._execution_engine
                if hasattr(self, "_execution_engine")
                else None,
            )
            tech_stack = recon_context.tech_stack if recon_context else None
            result = dr.run(
                targets=targets,
                budget=budget,
                aggressiveness=aggressiveness,
                auth_config=auth_config,
                tech_stack=tech_stack,
                skip_tools=None,
                recon_context=recon_context,
            )
            # No shadow_compare here — the agent already failed, so there is
            # no meaningful "old" result to compare against. Running the
            # pipeline a second time for comparison would waste resources.
            slog.tool_complete(
                "deterministic_fallback", success=True, findings=len(result)
            )
            return result

    def _maybe_run_browser_scanner(
        self,
        targets: list[str],
        recon_context,
        findings: list[dict],
    ) -> list[dict]:
        tech_stack = recon_context.tech_stack if recon_context else []
        # Use the shared SPA detection from browser_scanner module
        try:
            from tools.browser_scanner import is_spa_target
            from tools.browser_scanner import scan as run_browser_scan
        except ImportError:
            logger.debug("Browser scanner module not available — skipping browser scan")
            return findings
        if not is_spa_target(tech_stack):
            return findings
        try:
            for target in targets:
                emit_thinking(
                    self.engagement_id,
                    f"SPA detected — running browser scanner for {target}",
                )
                browser_findings = run_browser_scan(target, tech_stack=tech_stack)
                for bf in browser_findings:
                    norm = self._normalize_finding(bf, "browser_scanner")
                    if norm:
                        # Emit in real-time via StreamingFindingEmitter
                        try:
                            _finding_emitter = StreamingFindingEmitter(
                                self.engagement_id
                            )
                            _finding_emitter.emit_finding(norm)
                        except Exception:
                            logger.debug(
                                "Browser scanner finding emit skipped (non-fatal)",
                                exc_info=True,
                            )
                        findings.append(norm)
        except Exception as e:
            logger.warning("Browser scanner failed (non-fatal): %s", e)
        return findings

    def run_analysis(self, job: dict) -> dict:
        from orchestrator_pkg.analysis import (
            BudgetPersistenceService,
            IntelligenceService,
            LlmBatchService,
            SnapshotService,
        )

        slog = ScanLogger("orchestrator", engagement_id=self.engagement_id)
        slog.tool_start("orchestrator.run_analysis", [])
        self._check_timeout()
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="analyze",
        )
        self.logger.log_job_started(
            job_type="analyze",
            engagement_id=self.engagement_id,
        )

        db_conn = os.getenv("DATABASE_URL")
        if not db_conn:
            raise OSError(
                "DATABASE_URL is not set — cannot create snapshot for analysis"
            )

        # ── 1. SnapshotService — load findings, create snapshot, load budget ──
        snapshot_svc = SnapshotService(
            db_conn=db_conn,
            engagement_id=self.engagement_id,
            finding_repo=self.finding_repo,
            get_org_id_fn=self._get_org_id,
            load_priority_vuln_classes_fn=self._load_priority_vuln_classes,
            state=getattr(self, "state", None),
        )
        snapshot, budget_mgr, _findings, org_id = snapshot_svc.load_and_build(job)

        # ── 2. IntelligenceService — evaluate + synthesize ──
        intelligence_svc = IntelligenceService(
            db_conn=db_conn,
            engagement_id=self.engagement_id,
            llm_client=self.llm_client,
        )
        evaluation = intelligence_svc.evaluate(snapshot, org_id)
        synthesis, llm_svc, engagement_cost_tracker, recon_ctx, scored = (
            intelligence_svc.run_synthesis(evaluation, snapshot)
        )
        if synthesis.get("risk_level") or synthesis.get("executive_summary"):
            emit_thinking(
                self.engagement_id,
                f"LLM analysis: {synthesis.get('risk_level', 'unknown')} risk — "
                f"{synthesis.get('executive_summary', '')[:100]}...",
            )

        # ── 3. LlmBatchService — PoC, chain exploits, fixes ──
        from orchestrator_pkg.persistence import FindingPersistenceService

        _fps = FindingPersistenceService(
            engagement_id=self.engagement_id,
            finding_repo=self.finding_repo,
            bug_bounty_mode=self.bug_bounty_mode,
            classify_finding_type_fn=self._classify_finding_type,
            get_org_id_fn=self._get_org_id,
        )
        llm_batch_svc = LlmBatchService(
            llm_client=self.llm_client,
            engagement_id=self.engagement_id,
            save_poc_fn=_fps.save_poc,
            save_remediation_fn=_fps.save_remediation,
        )
        llm_batch_svc.generate_pocs(scored, llm_svc, engagement_cost_tracker)
        llm_batch_svc.generate_chain_exploits(llm_svc, engagement_cost_tracker)
        llm_batch_svc.generate_fixes(
            scored,
            recon_ctx,
            llm_svc,
            engagement_cost_tracker,
        )

        # ── 4. BudgetPersistenceService — persist budget counters ──
        BudgetPersistenceService.persist(budget_mgr)

        analysis = evaluation.get("analysis", {})
        slog.tool_complete(
            "orchestrator.run_analysis",
            success=True,
            findings=len(evaluation.get("scored_findings", [])),
        )
        slog.info(
            "Analysis complete — risk=%s, coverage_gaps=%d, high_value_targets=%d",
            analysis.get("risk_level", "unknown"),
            len(analysis.get("coverage_gaps", [])),
            len(analysis.get("high_value_targets", [])),
        )
        return {
            "phase": "analyze",
            "status": "completed",
            "actions": [],
            "analysis": analysis,
            "scored_findings": evaluation.get("scored_findings", []),
            "reasoning": evaluation.get("reasoning", ""),
            "synthesis": synthesis,
            "next_state": "reporting",
            "trace_id": get_trace_id(),
        }

    def run_reporting(self, job: dict) -> dict:
        from orchestrator_pkg.reporting import (
            ReportGenerationService,
            TargetProfileService,
        )

        slog = ScanLogger("orchestrator", engagement_id=self.engagement_id)
        slog.tool_start("orchestrator.run_reporting", [])
        self._check_timeout()
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="report",
        )
        self.logger.log_job_started(
            job_type="report",
            engagement_id=self.engagement_id,
        )

        # ── 1. ReportGenerationService — LLM report + SBOM ──
        report_svc = ReportGenerationService(
            engagement_id=self.engagement_id,
            llm_client=self.llm_client,
            llm_model=LLM_AGENT_MODEL,
        )
        report_data = report_svc.generate(job)

        # ── 2. TargetProfileService — target profile upsert ──
        profile_svc = TargetProfileService(
            engagement_id=self.engagement_id,
            finding_repo=self.finding_repo,
            get_org_id_fn=self._get_org_id,
        )
        profile_svc.update(job)

        # ── Scan diff dispatch removed from orchestrator ──
        # This is now handled by tasks/report.py::generate_report() which
        # queries the DB for the most recent completed engagement for the
        # same target URL. The DB-based approach is more reliable because
        # it doesn't depend on prev_engagement_id being set in the budget.

        slog.tool_complete("orchestrator.run_reporting", success=True)
        return {
            "phase": "report",
            "status": "completed",
            "next_state": "complete",
            "report": report_data,
            "trace_id": get_trace_id(),
        }

    def run_repo_scan(self, job: dict) -> dict:
        slog = ScanLogger("orchestrator", engagement_id=self.engagement_id)
        slog.tool_start(
            "orchestrator.run_repo_scan", [f"repo={job.get('repo_url', '')}"]
        )
        self._check_timeout()
        repo_url = job.get("repo_url")
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id, job_type="repo_scan", target=repo_url
        )
        self.logger.log_job_started(
            job_type="repo_scan", engagement_id=self.engagement_id, target=repo_url
        )
        repo_aggressiveness = job.get("aggressiveness", DEFAULT_AGGRESSIVENESS)
        custom_rules_path = job.get("custom_rules_path")
        try:
            findings = execute_repo_scan(
                self,
                repo_url,
                job.get("budget", {}),
                repo_aggressiveness,
                custom_rules_path,
            )
        except RuntimeError as e:
            err_str = str(e)
            if err_str.startswith("REPO_CLONE_FAILED:"):
                _, failed_url, reason = err_str.split(":", 2)
                logger.error("Repository clone failed for %s: %s", failed_url, reason)
                self.ws_publisher.publish_state_transition(
                    engagement_id=self.engagement_id,
                    from_state="recon",
                    to_state="failed",
                    reason=f"Repository clone failed: {reason[:200]}",
                )
                return {
                    "phase": "repo_scan",
                    "status": "failed",
                    "findings_count": 0,
                    "next_state": "failed",
                    "trace_id": get_trace_id(),
                }
            raise

        findings_count = len(findings)
        failed_saves = self._save_findings(findings)
        if failed_saves > 0:
            slog.warning(
                "%d/%d repo scan findings failed to save", failed_saves, findings_count
            )
        next_state = "scanning"
        if findings_count == 0:
            logger.info("Repository scan completed with no findings for %s", repo_url)

        if findings_count > 0:
            from orchestrator_pkg.recon_context_service import ReconContextService

            ReconContextService.build_and_save(
                engagement_id=self.engagement_id,
                findings=findings,
                repo_url=repo_url,
            )

        # The task handler already transitioned the DB from 'created' to 'recon'
        # before calling this method, so use 'recon' as the from_state
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="recon",
            to_state=next_state,
            reason="Repository scan completed — auto-advancing to web scan",
        )
        slog.tool_complete(
            "orchestrator.run_repo_scan", success=True, findings=findings_count
        )
        return {
            "phase": "repo_scan",
            "status": "completed",
            "findings_count": findings_count,
            "next_state": next_state,
            "trace_id": get_trace_id(),
        }

    def _get_org_id(self) -> str | None:
        """Get the org_id for the current engagement.

        Returns:
            org_id string, or None if unavailable
        """
        if self.engagement_repo:
            try:
                eng = self.engagement_repo.find_by_id(self.engagement_id)
                return str(eng["org_id"]) if eng and eng.get("org_id") else None
            except Exception as e:
                logger.warning(
                    "Failed to get org_id for engagement %s: %s", self.engagement_id, e
                )
        return None

    def _check_timeout(self):
        if self.start_time is None:
            return
        elapsed = time.time() - self.start_time
        if elapsed > HARD_TIMEOUT_SECONDS:
            self._log_timeout_event(elapsed)
            raise EngagementTimeoutError(
                f"Engagement {self.engagement_id} exceeded hard timeout "
                f"of {HARD_TIMEOUT_SECONDS} seconds (elapsed: {elapsed:.2f}s)"
            )

    def _get_scan_state(self) -> str:
        from orchestrator_pkg.engagement import EngagementService

        return EngagementService.get_scan_state(self.engagement_id)

    def _log_timeout_event(self, elapsed_seconds: float):
        from orchestrator_pkg.engagement import EngagementService

        EngagementService.log_timeout_event(self.engagement_id, elapsed_seconds)

    def get_elapsed_time(self) -> float:
        if self.start_time is None:
            return 0.0
        return time.time() - self.start_time

    def get_remaining_time(self) -> float:
        elapsed = self.get_elapsed_time()
        return max(0.0, HARD_TIMEOUT_SECONDS - elapsed)
