"""
Orchestrator - Workflow executor ONLY (no decision-making)
Executes actions generated by Intelligence Engine

Requirements: 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 21.1, 21.2, 31.2, 31.3
"""

import json
import logging
import os
import time

from config.constants import (
    DEFAULT_AGGRESSIVENESS,
    HARD_TIMEOUT_SECONDS,
    LLM_AGENT_MODEL,
)
from database.connection import connect
from database.repositories.engagement_repository import EngagementRepository
from database.repositories.finding_repository import FindingRepository
from llm_client import LLMClient
from mcp_server import get_mcp_server
from models.recon_context import ReconContext
from parsers.normalizer import FindingNormalizer
from parsers.parser import Parser
from pipeline_router import execute_recon_pipeline, execute_scan_pipeline
from streaming import (
    emit_state_change,
    emit_thinking,
    emit_tool_complete,
    emit_tool_start,
    get_stream_manager,
)
from tasks.utils import load_recon_context, save_recon_context
from tools.llm_payload_generator import LLMPayloadGenerator
from tools.tool_runner import ToolRunner
from tracing import (
    ExecutionSpan,
    StructuredLogger,
    TracingManager,
    get_trace_id,
)
from websocket_events import get_websocket_publisher

from .repo_scan import execute_repo_scan

logger = logging.getLogger(__name__)


class EngagementTimeoutError(Exception):
    """Raised when engagement exceeds hard timeout"""

    pass


class Orchestrator:
    """
    Workflow execution engine.
    Executes actions generated by Intelligence Engine without making decisions.
    """

    def __init__(self, engagement_id: str, trace_id: str = None):
        self.engagement_id = engagement_id
        self.start_time = None
        self.trace_id = trace_id

        db_conn = os.getenv("DATABASE_URL")
        self.tracing_manager = TracingManager(db_conn)
        self.logger = StructuredLogger(db_conn)
        self.span_recorder = ExecutionSpan(db_conn)
        self.ws_publisher = get_websocket_publisher()
        self.tool_runner = ToolRunner(
            connection_string=db_conn, engagement_id=self.engagement_id
        )
        self.parser = Parser(connection_string=db_conn)
        self.normalizer = FindingNormalizer()
        self.finding_repo = FindingRepository(db_conn) if db_conn else None
        self.engagement_repo = EngagementRepository(db_conn) if db_conn else None

        self.llm_client = None
        self.llm_payload_generator = None
        try:
            redis_url = os.getenv("REDIS_URL", "redis://localhost:6379")
            self.llm_client = LLMClient(redis_url=redis_url)
            if self.llm_client.is_available():
                from config.constants import LLM_PAYLOAD_GENERATION_MODEL
                from llm_client import load_llm_setting

                llm_payload_enabled = (
                    load_llm_setting("llm_payload_generation_enabled", "true") == "true"
                )
                if llm_payload_enabled:
                    self.llm_payload_generator = LLMPayloadGenerator(
                        llm_client=self.llm_client,
                        model=LLM_PAYLOAD_GENERATION_MODEL,
                    )
                    logger.info("LLM payload generator initialized")
        except Exception as e:
            logger.warning(f"LLM components not available (graceful degradation): {e}")

        self.mcp = get_mcp_server()
        self.stream = get_stream_manager()
        self._register_mcp_tools()
        self._last_agent_tried_tools = set()

    def _register_mcp_tools(self):
        from tool_definitions import build_mcp_tool_definitions
        for tool in build_mcp_tool_definitions():
            self.mcp.register_tool(tool)

    def mcp_run(self, tool: str, arguments: dict = None) -> dict:
        emit_tool_start(self.engagement_id, tool, list((arguments or {}).keys()))
        result = self.mcp.call_tool(tool, arguments)
        success = not result.get("isError", False)
        emit_tool_complete(
            self.engagement_id, tool, success,
            result.get("meta", {}).get("duration_ms", 0),
        )
        return result

    def _load_custom_rules(self, engagement_id: str) -> list[dict]:
        db_conn = os.getenv("DATABASE_URL")
        if not db_conn:
            return []
        try:
            conn = connect(db_conn)
            cursor = conn.cursor()
            cursor.execute("SELECT org_id FROM engagements WHERE id = %s", (engagement_id,))
            row = cursor.fetchone()
            if not row:
                cursor.close(); conn.close(); return []
            org_id = row[0]
            cursor.execute("""
                SELECT id, name, description, severity, category, rule_yaml, tags
                FROM custom_rules WHERE org_id = %s AND status = 'active'
                ORDER BY created_at DESC
            """, (org_id,))
            columns = [desc[0] for desc in cursor.description]
            rules = [dict(zip(columns, row, strict=False)) for row in cursor.fetchall()]
            cursor.close(); conn.close()
            return rules
        except Exception as e:
            logger.warning(f"Failed to load custom rules: {e}")
            return []

    def run(self, job: dict) -> dict:
        if self.start_time is None:
            self.start_time = time.time()
        self._check_timeout()
        job_type = job.get("type")
        with self.span_recorder.span(ExecutionSpan.SPAN_ORCHESTRATOR_STEP):
            self.logger.log("orchestrator_step", f"Routing job: {job_type}",
                            {"job_type": job_type, "engagement_id": self.engagement_id})
            if job_type == "recon":
                return self.run_recon(job)
            elif job_type == "scan":
                return self.run_scan(job)
            elif job_type == "analyze":
                return self.run_analysis(job)
            elif job_type == "report":
                return self.run_reporting(job)
            elif job_type == "repo_scan":
                return self.run_repo_scan(job)
            else:
                raise ValueError(f"Unknown job type: {job_type}")

    def run_recon(self, job: dict) -> dict:
        self._check_timeout()
        target = job.get("target")
        if not target:
            targets_list = job.get("targets", [])
            target = targets_list[0] if targets_list else None
        if not target:
            logger.warning(f"run_recon called with no target for engagement {self.engagement_id}, skipping")
            return {"phase": "recon", "status": "skipped", "findings_count": 0,
                    "next_state": "scanning", "trace_id": get_trace_id()}

        self.ws_publisher.publish_job_started(engagement_id=self.engagement_id, job_type="recon", target=target)
        self.logger.log_job_started(job_type="recon", engagement_id=self.engagement_id, target=target)
        emit_thinking(self.engagement_id, f"Starting reconnaissance against {target}")
        emit_state_change(self.engagement_id, "created", "recon", "Starting reconnaissance")

        aggressiveness = job.get("aggressiveness", DEFAULT_AGGRESSIVENESS)
        findings, recon_context = execute_recon_pipeline(self, target, job.get("budget", {}), aggressiveness)

        findings_count = len(findings)
        self._save_findings(findings, "tool")

        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id, from_state=self._get_scan_state(),
            to_state="scanning", reason="Reconnaissance completed — auto-advancing to scan",
        )

        if recon_context:
            try:
                save_recon_context(self.engagement_id, recon_context)
            except Exception as e:
                logger.warning(f"Failed to save recon context to Redis: {e}")

        return {
            "phase": "recon", "status": "completed", "findings_count": findings_count,
            "next_state": "scanning",
            "recon_context": recon_context.to_dict() if hasattr(recon_context, "to_dict") else recon_context,
            "trace_id": get_trace_id(),
        }

    def _normalize_finding(self, raw_finding: dict, tool: str) -> dict | None:
        try:
            finding = self.normalizer.normalize(raw_finding, tool)
            return {
                "type": finding.type,
                "severity": finding.severity.value if hasattr(finding.severity, "value") else finding.severity,
                "endpoint": finding.endpoint,
                "evidence": finding.evidence,
                "confidence": finding.confidence,
                "source_tool": tool,
            }
        except Exception as e:
            logger.warning(f"Failed to normalize finding: {e}")
            return None

    def _save_findings(self, findings: list[dict], source_tool_key: str = "source_tool"):
        if not self.finding_repo or not findings:
            return

        # Normalize heterogeneous inputs to plain dicts
        normalized_inputs: list[dict] = []
        for item in findings:
            if isinstance(item, dict):
                normalized_inputs.append(item)
                continue
            if hasattr(item, "tool") and hasattr(item, "output"):
                logger.warning(f"_save_findings received unparsed tool result for tool "
                               f"'{getattr(item, 'tool', 'unknown')}' — skipping.")
                continue
            if hasattr(item, "findings") and isinstance(item.findings, list):
                for f in item.findings:
                    if isinstance(f, dict):
                        normalized_inputs.append(f)
                continue
            try:
                normalized_inputs.append(vars(item))
            except Exception:
                logger.warning(f"_save_findings: cannot coerce {type(item)} to dict, skipping")
        findings = normalized_inputs
        if not findings:
            return

        _pgvector = None
        _llm_client = None

        def _get_embedding(text: str) -> list[float] | None:
            nonlocal _llm_client
            api_key = None
            try:
                if _llm_client is None:
                    from llm_client import LLMClient
                    _llm_client = LLMClient()
                api_key = _llm_client.api_key
            except Exception:
                pass
            if api_key:
                try:
                    import httpx
                    resp = httpx.post(
                        "https://api.openai.com/v1/embeddings",
                        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                        json={"model": "text-embedding-3-small", "input": text},
                        timeout=15,
                    )
                    if resp.status_code == 200:
                        data = resp.json()
                        return data["data"][0]["embedding"]
                except Exception as e:
                    logger.debug(f"OpenAI embedding API failed (non-fatal): {e}")
            from database.repositories.pgvector_repository import PGVectorRepository
            return PGVectorRepository()._generate_embedding_fallback(text)

        def _find_existing_similar(text: str, threshold: float = 0.92) -> dict | None:
            nonlocal _pgvector
            if _pgvector is None:
                from database.repositories.pgvector_repository import PGVectorRepository
                _pgvector = PGVectorRepository()
            if not _pgvector.check_pgvector_available():
                return None
            embedding = _get_embedding(text)
            if not embedding:
                return None
            try:
                from database.connection import db_cursor
                emb_str = "[" + ",".join(map(str, embedding)) + "]"
                with db_cursor() as cursor:
                    cursor.execute("""
                        SELECT f.id, f.type, f.severity, f.endpoint,
                               1 - (f.embedding <=> %s::vector) AS similarity
                        FROM findings f
                        WHERE f.engagement_id = %s AND f.embedding IS NOT NULL
                          AND (f.embedding <=> %s::vector) <= (1 - %s)
                        ORDER BY f.embedding <=> %s::vector LIMIT 1
                    """, (emb_str, self.engagement_id, emb_str, threshold, emb_str))
                    row = cursor.fetchone()
                    if row and float(row[4]) >= threshold:
                        return {"id": str(row[0]), "similarity": float(row[4])}
            except Exception as e:
                logger.debug(f"Similarity check failed (non-fatal): {e}")
            return None

        try:
            for finding in findings:
                if not finding.get("cvss_score"):
                    try:
                        from cvss_calculator import estimate_cvss
                        finding["cvss_score"] = estimate_cvss(
                            finding_type=finding.get("type", ""),
                            severity=finding.get("severity", "MEDIUM"),
                            evidence_strength=finding.get("evidence_strength", "moderate"),
                        )
                    except Exception as cvss_err:
                        logger.warning(f"CVSS estimation failed (non-fatal): {cvss_err}")

                SECRET_TOOLS = {"gitleaks", "trufflehog", "secret-scan"}
                st = finding.get("tool") or finding.get("source_tool") or "unknown"
                if st in SECRET_TOOLS or finding.get("type", "").startswith("COMMITTED_SECRET"):
                    saved_id = self.finding_repo.upsert_secret_finding(
                        engagement_id=self.engagement_id,
                        finding_type=finding.get("type", "UNKNOWN"),
                        severity=finding.get("severity", "INFO"),
                        endpoint=finding.get("endpoint", ""),
                        evidence=finding.get("evidence", {}),
                        confidence=finding.get("confidence", 0.5),
                        source_tool=st,
                        cvss_score=finding.get("cvss_score"),
                    )
                else:
                    dedup_text = f"{finding.get('type', '')} {finding.get('endpoint', '')} {finding.get('evidence', {}).get('payload', '')}"
                    similar = _find_existing_similar(dedup_text)
                    if similar:
                        try:
                            from database.connection import db_cursor
                            with db_cursor() as cursor:
                                cursor.execute(
                                    "UPDATE findings SET last_seen_at = NOW(), severity = %s, confidence = %s, evidence = %s WHERE id = %s",
                                    (finding.get("severity", "INFO"), finding.get("confidence", 0.5),
                                     json.dumps(finding.get("evidence", {})), similar["id"]),
                                )
                            saved_id = similar["id"]
                            logger.debug(f"Updated existing finding {similar['id']} (similarity={similar['similarity']:.3f})")
                        except Exception:
                            saved_id = self.finding_repo.create_finding(
                                engagement_id=self.engagement_id,
                                finding_type=finding.get("type", "UNKNOWN"),
                                severity=finding.get("severity", "INFO"),
                                endpoint=finding.get("endpoint", ""),
                                evidence=finding.get("evidence", {}),
                                confidence=finding.get("confidence", 0.5),
                                source_tool=st,
                                cvss_score=finding.get("cvss_score"),
                            )
                    else:
                        saved_id = self.finding_repo.create_finding(
                            engagement_id=self.engagement_id,
                            finding_type=finding.get("type", "UNKNOWN"),
                            severity=finding.get("severity", "INFO"),
                            endpoint=finding.get("endpoint", ""),
                            evidence=finding.get("evidence", {}),
                            confidence=finding.get("confidence", 0.5),
                            source_tool=st,
                            cvss_score=finding.get("cvss_score"),
                        )

                if saved_id and finding.get("type") not in ("", "UNKNOWN") and finding.get("endpoint"):
                    try:
                        emb_text = f"{finding.get('type', '')} {finding.get('endpoint', '')} {finding.get('evidence', {}).get('payload', '')}"
                        embedding = _get_embedding(emb_text)
                        if embedding:
                            from database.repositories.pgvector_repository import (
                                PGVectorRepository,
                            )
                            pg = PGVectorRepository()
                            pg.store_embedding(saved_id, self.engagement_id, embedding, emb_text)
                    except Exception as e:
                        logger.debug(f"Embedding storage failed (non-fatal): {e}")

                if saved_id and finding.get("severity", "").upper() in ("CRITICAL", "HIGH"):
                    try:
                        from post_finding_hooks import fire_finding_webhooks
                        fire_finding_webhooks({
                            "id": saved_id, "engagement_id": self.engagement_id,
                            "type": finding.get("type"), "severity": finding.get("severity"),
                            "endpoint": finding.get("endpoint"), "source_tool": st,
                            "confidence": finding.get("confidence", 0),
                        })
                    except Exception as hook_err:
                        logger.warning(f"Webhook dispatch failed (non-fatal): {hook_err}")
        except Exception as e:
            logger.error(f"Failed to save findings: {e}")

    def _save_poc_to_finding(self, finding_id: str, poc_data: dict) -> bool:
        """Save PoC data to findings.poc_generated column.

        Args:
            finding_id: UUID of the finding
            poc_data: PoC dict from PoCGenerator

        Returns:
            True if saved successfully
        """
        import json

        from database.connection import connect

        conn = None
        try:
            conn = connect(os.getenv("DATABASE_URL"))
            cursor = conn.cursor()
            cursor.execute(
                """
                UPDATE findings
                SET poc_generated = %s::jsonb,
                    poc_generated_at = NOW()
                WHERE id = %s
                """,
                (json.dumps(poc_data), finding_id),
            )
            conn.commit()
            return cursor.rowcount > 0
        except Exception as e:
            logger.warning(
                "Failed to save PoC for finding %s: %s",
                finding_id, e,
            )
            if conn:
                try:
                    conn.rollback()
                except Exception:
                    pass
            return False
        finally:
            if conn:
                try:
                    conn.close()
                except Exception:
                    pass

    def _save_remediation_fix(
        self, finding_id: str, fix_data: dict
    ) -> bool:
        """Save remediation fix to findings.remediation_fix column.

        Args:
            finding_id: UUID of the finding
            fix_data: Fix dict from DeveloperFixAssistant

        Returns:
            True if saved successfully
        """
        import json

        from database.connection import connect

        conn = None
        try:
            conn = connect(os.getenv("DATABASE_URL"))
            cursor = conn.cursor()
            cursor.execute(
                """
                UPDATE findings
                SET remediation_fix = %s::jsonb,
                    remediation_fix_at = NOW()
                WHERE id = %s
                """,
                (json.dumps(fix_data), finding_id),
            )
            conn.commit()
            return cursor.rowcount > 0
        except Exception as e:
            logger.warning(
                "Failed to save remediation fix: %s", e
            )
            if conn:
                try:
                    conn.rollback()
                except Exception:
                    pass
            return False
        finally:
            if conn:
                try:
                    conn.close()
                except Exception:
                    pass

    def run_scan_with_agent(self, targets, recon_context, aggressiveness=DEFAULT_AGGRESSIVENESS,
                            authorized_scope=None, auth_config=None):
        from agent import AgentResult, create_phase_agent
        from database.repositories.agent_decision_repository import (
            AgentDecisionRepository,
        )
        from tools.scope_validator import ScopeValidator, ScopeViolationError

        db_conn = os.getenv("DATABASE_URL")
        decision_repo = AgentDecisionRepository(db_conn) if db_conn else None
        all_findings = []

        for target in targets:
            try:
                agent = create_phase_agent(
                    phase="scan", tool_runner=self.tool_runner,
                    engagement_id=self.engagement_id, llm_client=self.llm_client,
                    decision_repo=decision_repo,
                )
                if authorized_scope:
                    scope_validator = ScopeValidator(self.engagement_id, authorized_scope)
                    original_call = agent.registry.call
                    def scoped_call(name, **kwargs):
                        tgt = kwargs.get("target", "")
                        if tgt:
                            try:
                                scope_validator.validate_target(tgt)
                            except ScopeViolationError as e:
                                logger.warning(f"Scope violation blocked: {e}")
                                emit_thinking(self.engagement_id, f"Blocked: {tgt} is out of scope")
                                return AgentResult(tool=name, success=False, error=f"Scope violation: {e}")
                        return original_call(name, **kwargs)
                    agent.registry.call = scoped_call

                emit_thinking(self.engagement_id, f"LLM agent selecting scan tools for {target}...")
                results = agent.run(
                    task=f"scan: {target}",
                    initial_context={"recon_context": recon_context, "target": target},
                    recon_context=recon_context,
                )

                agent_ran_tools = {r.tool for r in results if r.success}
                logger.info(f"Agent ran tools: {agent_ran_tools}")
                self._last_agent_tried_tools.update(agent_ran_tools)

                for r in results:
                    if r.success and r.output:
                        parsed = self.parser.parse(r.tool, r.output)
                        for p in parsed:
                            norm = self._normalize_finding(p, r.tool)
                            if norm:
                                all_findings.append(norm)
            except Exception as e:
                logger.warning(f"Agent scan failed for {target}: {e}. Falling back.")
                fallback = execute_scan_pipeline(self, [target], {}, aggressiveness, auth_config,
                                                  recon_context.tech_stack if recon_context else None)
                all_findings.extend(fallback)

        return all_findings

    def run_scan(self, job: dict) -> dict:
        self._check_timeout()
        targets = job.get("targets", [])
        self.ws_publisher.publish_job_started(engagement_id=self.engagement_id, job_type="scan", target=str(targets))
        self.logger.log_job_started(job_type="scan", engagement_id=self.engagement_id, target=str(targets))

        custom_rules = self._load_custom_rules(self.engagement_id)
        if custom_rules:
            for rule in custom_rules:
                self.ws_publisher.publish_scanner_activity(
                    engagement_id=self.engagement_id, tool_name="Custom Rules Engine",
                    activity="custom rule loaded", status="completed", target=str(targets),
                    details=f"{rule.get('name', 'unknown')} ({rule.get('severity', 'unknown')}) — {rule.get('description', '')[:120]}",
                )
            logger.info(f"Loaded {len(custom_rules)} custom rule(s) for engagement {self.engagement_id}")

        scan_aggressiveness = job.get("aggressiveness", DEFAULT_AGGRESSIVENESS)
        scan_mode = job.get("scan_mode", "agent")
        recon_context = load_recon_context(self.engagement_id)
        agent_mode_enabled = job.get("agent_mode", True)
        auth_config = job.get("auth_config", {})

        # ── Swarm mode: parallel specialist agents ──
        if (
            scan_mode == "swarm"
            and recon_context is not None
            and self.llm_client is not None
            and self.llm_client.is_available()
        ):
            emit_thinking(
                self.engagement_id,
                "Multi-agent swarm mode active — "
                "spawning specialist agents...",
            )

            from agent.swarm import SwarmOrchestrator
            from database.repositories.agent_decision_repository import (
                AgentDecisionRepository,
            )
            from llm_service import LLMService
            decision_repo = AgentDecisionRepository(
                os.getenv("DATABASE_URL")
            ) if os.getenv("DATABASE_URL") else None

            llm_svc = LLMService(llm_client=self.llm_client)
            swarm = SwarmOrchestrator(
                llm_service=llm_svc,
                tool_runner=self.tool_runner,
                recon_context=recon_context,
                engagement_id=self.engagement_id,
                decision_repo=decision_repo,
            )

            swarm_findings = swarm.run(timeout=1800)
            logger.info(
                "Swarm returned %d findings", len(swarm_findings)
            )

            # Safety net: run tools the swarm didn't cover
            swarm_tools: set[str] = set()
            for f in swarm_findings:
                st = f.get("source_tool") or f.get("tool")
                if st:
                    swarm_tools.add(st)

            tech_stack = (
                recon_context.tech_stack if recon_context else None
            )
            safety_findings = execute_scan_pipeline(
                self, targets, job.get("budget", {}),
                scan_aggressiveness, auth_config, tech_stack,
                skip_tools=swarm_tools,
            )

            findings = swarm_findings + safety_findings

        # ── Agent mode: LLM-driven single agent ──
        elif (
            agent_mode_enabled
            and recon_context is not None
            and self.llm_client is not None
            and self.llm_client.is_available()
        ):
            emit_thinking(self.engagement_id, "LLM agent mode active — analyzing recon results and selecting scan tools...")
            findings = self.run_scan_with_agent(targets, recon_context, scan_aggressiveness, auth_config=auth_config)
            agent_tried = getattr(self, "_last_agent_tried_tools", set())
            logger.info(f"Agent scan complete — safety net skipping agent tools: {agent_tried}")
            tech_stack = recon_context.tech_stack if recon_context else None
            deterministic_findings = execute_scan_pipeline(
                self, targets, job.get("budget", {}), scan_aggressiveness,
                auth_config, tech_stack, skip_tools=agent_tried,
            )
            findings.extend(deterministic_findings)

        # ── Deterministic mode: no AI ──
        else:
            mode = "deterministic"
            if not recon_context: mode += " (no recon context)"
            elif not agent_mode_enabled: mode += " (agent mode disabled)"
            else: mode += " (LLM unavailable)"
            logger.info(f"Running {mode} scan")
            tech_stack = recon_context.tech_stack if recon_context else None
            findings = execute_scan_pipeline(self, targets, job.get("budget", {}), scan_aggressiveness, auth_config, tech_stack)

        try:
            from tools.browser_scanner import scan as run_browser_scan
            tech = recon_context.tech_stack if recon_context else (tech_stack or [])
            tech_str = " ".join(tech).lower()
            if any(f in tech_str for f in ["react", "vue", "angular", "next", "nuxt", "svelte"]):
                for target in targets:
                    emit_thinking(self.engagement_id, f"SPA detected — running browser scanner for {target}")
                    browser_findings = run_browser_scan(target, tech_stack=tech)
                    for bf in browser_findings:
                        norm = self._normalize_finding(bf, "browser_scanner")
                        if norm:
                            findings.append(norm)
        except ImportError:
            pass
        except Exception as e:
            logger.warning(f"Browser scanner failed (non-fatal): {e}")

        findings_count = len(findings)
        self._save_findings(findings)

        from llm_client import load_llm_setting
        llm_review_enabled = load_llm_setting("llm_review_enabled", "true") == "true"
        if llm_review_enabled and self.llm_client and self.llm_client.is_available():
            try:
                from tasks.llm_review import run_llm_review
                run_llm_review.delay(engagement_id=self.engagement_id, budget=job.get("budget", {}), trace_id=get_trace_id())
                logger.info(f"Enqueued LLM review for engagement {self.engagement_id}")
            except Exception as e:
                logger.warning(f"Failed to enqueue LLM review (non-fatal): {e}")

        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id, from_state="scanning", to_state="analyzing", reason="Scanning completed",
        )
        return {"phase": "scan", "status": "completed", "findings_count": findings_count,
                "next_state": "analyzing", "trace_id": get_trace_id()}

    def run_analysis(self, job: dict) -> dict:
        self._check_timeout()
        self.ws_publisher.publish_job_started(engagement_id=self.engagement_id, job_type="analyze")
        self.logger.log_job_started(job_type="analyze", engagement_id=self.engagement_id)
        findings = []
        if self.finding_repo:
            try:
                raw_findings, _ = self.finding_repo.get_findings_by_engagement(self.engagement_id)
                findings = [f.to_dict() if hasattr(f, "to_dict") else dict(f) if isinstance(f, dict) else f for f in raw_findings]
            except Exception as e:
                logger.warning(f"Failed to load findings: {e}")

        from intelligence_engine import IntelligenceEngine
        from loop_budget_manager import LoopBudgetManager
        from snapshot_manager import SnapshotManager
        db_conn = os.getenv("DATABASE_URL")
        if not db_conn:
            raise OSError("DATABASE_URL is not set — cannot create snapshot for analysis")
        snapshot_mgr = SnapshotManager(db_conn)
        snapshot = snapshot_mgr.create_snapshot(self.engagement_id)
        budget_config = job.get("budget", {})
        budget_mgr = LoopBudgetManager(self.engagement_id, budget_config)
        engine = IntelligenceEngine(db_conn)
        snapshot["findings"] = findings
        snapshot["loop_budget"] = budget_mgr.to_dict()
        # Load org_id for learned FP rate lookups in IntelligenceEngine
        org_id = self._get_org_id()
        snapshot["org_id"] = org_id
        evaluation = engine.evaluate(snapshot, org_id=org_id)

        synthesis = {}
        if self.llm_client and self.llm_client.is_available():
            try:
                from llm_service import LLMService
                from llm_synthesizer import LLMSynthesizer
                llm_svc = LLMService(self.llm_client)
                recon_ctx = load_recon_context(self.engagement_id)
                synthesizer = LLMSynthesizer(llm_svc)
                synthesis = synthesizer.synthesize(
                    scored_findings=evaluation.get("scored_findings", []),
                    attack_paths=snapshot.get("attack_graph", {}).get("paths", []),
                    recon_context=recon_ctx,
                )
                emit_thinking(self.engagement_id, f"LLM analysis: {synthesis.get('risk_level', 'unknown')} risk — "
                              f"{synthesis.get('executive_summary', '')[:100]}...")
            except Exception as e:
                logger.warning(f"LLM synthesis failed (non-fatal): {e}")

        # ── PoC Generation for HIGH/CRITICAL findings ──
        try:
            from poc_generator import PoCGenerator
            from tasks.utils import LlmCostTracker

            poc_gen = PoCGenerator(llm_client=self.llm_client)
            scored = evaluation.get("scored_findings", [])

            cost_tracker = None
            llm_svc = None
            if self.llm_client and self.llm_client.is_available():
                from llm_service import LLMService
                llm_svc = LLMService(llm_client=self.llm_client)
                from config.constants import LLM_MAX_COST_PER_ENGAGEMENT
                cost_tracker = LlmCostTracker(
                    engagement_id=self.engagement_id,
                    max_cost=LLM_MAX_COST_PER_ENGAGEMENT,
                )

            if cost_tracker and llm_svc:
                from concurrent.futures import ThreadPoolExecutor

                poc_futures = []
                with ThreadPoolExecutor(max_workers=4) as pool:
                    # Cap at 10 PoCs per engagement to prevent cost blow-up
                    for finding in scored[:10]:
                        future = pool.submit(
                            poc_gen.generate,
                            finding, llm_svc, cost_tracker,
                        )
                        poc_futures.append((finding, future))

                    for finding, future in poc_futures:
                        try:
                            poc = future.result(timeout=30)
                            if poc and finding.get("id"):
                                self._save_poc_to_finding(
                                    finding["id"], poc
                                )
                        except Exception as e:
                            logger.debug(
                                "PoC for finding %s failed: %s",
                                finding.get("id", "?"), e,
                            )
        except Exception as e:
            logger.warning(
                "PoC generation batch failed (non-fatal): %s", e
            )

        # ── Developer Fix Generation for MEDIUM+ findings ──
        try:
            from developer_fix_assistant import (
                DeveloperFixAssistant,
            )

            fix_assistant = DeveloperFixAssistant(
                llm_client=self.llm_client
            )

            # Re-use cost_tracker and llm_svc from PoC section
            if cost_tracker and llm_svc:
                from concurrent.futures import (
                    ThreadPoolExecutor,
                )

                # Get tech stack from recon context
                tech_stack: list[str] = []
                recon_ctx = load_recon_context(self.engagement_id)
                if recon_ctx:
                    tech_stack = (
                        recon_ctx.tech_stack
                        if hasattr(recon_ctx, "tech_stack")
                        else []
                    ) or []

                fix_futures = []
                with ThreadPoolExecutor(max_workers=4) as pool:
                    # Cap at 15 fixes per engagement
                    for finding in scored[:15]:
                        future = pool.submit(
                            fix_assistant.generate,
                            finding,
                            tech_stack,
                            llm_svc,
                            cost_tracker,
                        )
                        fix_futures.append((finding, future))

                    for finding, future in fix_futures:
                        try:
                            fix = future.result(timeout=45)
                            if fix and finding.get("id"):
                                self._save_remediation_fix(
                                    finding["id"], fix
                                )
                        except Exception as e:
                            logger.debug(
                                "Fix for finding %s failed: %s",
                                finding.get("id", "?"),
                                e,
                            )
        except Exception as e:
            logger.warning(
                "Fix generation batch failed (non-fatal): %s", e
            )

        actions = evaluation.get("actions", [])
        next_state = "reporting"
        for action in actions:
            can_continue, reason = budget_mgr.can_continue(action)
            if can_continue:
                budget_mgr.consume(action)
                next_state = "recon"
            else:
                logger.info(f"Budget exhausted: {reason}")

        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id, from_state="analyzing", to_state=next_state,
            reason="Analysis completed" if next_state == "reporting" else "Additional targets discovered",
        )
        return {"phase": "analyze", "status": "completed", "actions": actions,
                "scored_findings": evaluation.get("scored_findings", []),
                "reasoning": evaluation.get("reasoning", ""), "synthesis": synthesis,
                "next_state": next_state, "trace_id": get_trace_id()}

    def run_reporting(self, job: dict) -> dict:
        self._check_timeout()
        self.ws_publisher.publish_job_started(engagement_id=self.engagement_id, job_type="report")
        self.logger.log_job_started(job_type="report", engagement_id=self.engagement_id)
        report_data = {}
        if self.llm_client and self.llm_client.is_available():
            try:
                from database.repositories.report_repository import ReportRepository
                from llm_report_generator import LLMReportGenerator
                from llm_service import LLMService
                recon_ctx = load_recon_context(self.engagement_id)
                scored_findings = job.get("scored_findings", [])
                synthesis = job.get("synthesis", {})
                llm_svc = LLMService(self.llm_client)
                generator = LLMReportGenerator(llm_svc)
                engagement_info = {"target_url": job.get("target", ""), "scan_type": job.get("type", "")}
                report_data = generator.generate_report(
                    synthesis=synthesis, scored_findings=scored_findings,
                    engagement=engagement_info, recon_context=recon_ctx,
                )
                repo = ReportRepository()
                sbom_json = None
                try:
                    from database.repositories.finding_repository import (
                        FindingRepository,
                    )
                    from tools.sbom_generator import generate_sbom_from_findings
                    fr = FindingRepository()
                    all_findings, _ = fr.get_findings_by_engagement(self.engagement_id)
                    sbom_json = generate_sbom_from_findings(
                        engagement_id=self.engagement_id, findings=all_findings,
                        target_url=job.get("target", ""), repo_url=job.get("repo_url", ""),
                    )
                except Exception as e:
                    logger.warning(f"SBOM generation failed (non-fatal): {e}")
                repo.upsert_report(engagement_id=self.engagement_id, report_data=report_data,
                                   model_used=LLM_AGENT_MODEL, sbom_json=sbom_json)
                emit_thinking(self.engagement_id, "LLM report generated successfully")
            except Exception as e:
                logger.warning(f"LLM report generation failed (non-fatal): {e}")

        # ── Update target profile with findings from this engagement ──
        _org_id = self._get_org_id()
        try:
            from urllib.parse import urlparse

            from database.repositories.target_profile_repository import (
                TargetProfileRepository,
            )
            from database.repositories.tool_accuracy_repository import (
                ToolAccuracyRepository,
            )

            target_url = job.get("target", "")
            target_domain = urlparse(target_url).netloc
            if target_domain and _org_id:
                profile_repo = TargetProfileRepository(
                    os.getenv("DATABASE_URL")
                )

                # Load findings from this engagement
                all_findings, _ = (
                    self.finding_repo.get_findings_by_engagement(
                        self.engagement_id
                    )
                    if self.finding_repo
                    else ([], None)
                )

                # Load recon context from Redis
                recon_ctx = load_recon_context(self.engagement_id)
                recon_ctx_dict = (
                    recon_ctx.to_dict()
                    if hasattr(recon_ctx, "to_dict")
                    else {}
                )

                # Load tool accuracy for noisy-tool detection
                acc_repo = ToolAccuracyRepository(
                    os.getenv("DATABASE_URL")
                )
                fp_rates = acc_repo.load_fp_rates(_org_id)

                profile_repo.upsert_from_engagement(
                    org_id=_org_id,
                    target_url=target_url,
                    engagement_id=self.engagement_id,
                    recon_context=recon_ctx_dict,
                    findings=[
                        f.to_dict() if hasattr(f, "to_dict") else dict(f)
                        for f in (all_findings or [])
                    ],
                    tool_accuracy_fp_rates=fp_rates,
                )
                logger.info(
                    "Target profile updated for %s", target_domain
                )
        except Exception as e:
            logger.warning(
                "Target profile update failed (non-fatal): %s", e
            )

        # ── Dispatch scan diff for scheduled engagements ──
        try:
            _budget = job.get("budget", {})
            prev_id = _budget.get("prev_engagement_id") if _budget else None
            if prev_id and _org_id:
                from tasks.diff import run_scan_diff
                run_scan_diff.delay(
                    prev_engagement_id=prev_id,
                    new_engagement_id=self.engagement_id,
                    org_id=_org_id,
                )
        except Exception as e:
            logger.warning(
                "Scan diff dispatch failed (non-fatal): %s", e
            )

        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id, from_state="reporting", to_state="complete",
            reason="Reporting completed",
        )
        return {"phase": "report", "status": "completed", "next_state": "complete",
                "report": report_data, "trace_id": get_trace_id()}

    def run_repo_scan(self, job: dict) -> dict:
        self._check_timeout()
        repo_url = job.get("repo_url")
        self.ws_publisher.publish_job_started(engagement_id=self.engagement_id, job_type="repo_scan", target=repo_url)
        self.logger.log_job_started(job_type="repo_scan", engagement_id=self.engagement_id, target=repo_url)
        repo_aggressiveness = job.get("aggressiveness", DEFAULT_AGGRESSIVENESS)
        custom_rules_path = job.get("custom_rules_path")
        try:
            findings = execute_repo_scan(self, repo_url, job.get("budget", {}), repo_aggressiveness, custom_rules_path)
        except RuntimeError as e:
            err_str = str(e)
            if err_str.startswith("REPO_CLONE_FAILED:"):
                _, failed_url, reason = err_str.split(":", 2)
                logger.error(f"Repository clone failed for {failed_url}: {reason}")
                self.ws_publisher.publish_state_transition(
                    engagement_id=self.engagement_id, from_state="recon", to_state="failed",
                    reason=f"Repository clone failed: {reason[:200]}",
                )
                return {"phase": "repo_scan", "status": "failed", "findings_count": 0, "next_state": "failed", "trace_id": get_trace_id()}
            raise

        findings_count = len(findings)
        self._save_findings(findings, source_tool_key="tool")
        next_state = "scanning"
        if findings_count == 0:
            logger.info(f"Repository scan completed with no findings for {repo_url}")

        if findings_count > 0:
            try:
                vuln_types = list({f.get("type", "UNKNOWN") for f in findings})
                severity_breakdown = {}
                critical_files = []
                has_secrets = False
                dep_vulns = 0
                for f in findings:
                    sev = f.get("severity", "INFO")
                    severity_breakdown[sev] = severity_breakdown.get(sev, 0) + 1
                    if sev in ("CRITICAL", "HIGH"):
                        fp = f.get("file_path") or f.get("endpoint", "")
                        if fp and fp not in critical_files:
                            critical_files.append(fp)
                    if f.get("type") in ("EXPOSED_SECRET", "COMMITTED_SECRET", "HARDCODED_SECRET"):
                        has_secrets = True
                    if f.get("type") == "DEPENDENCY_VULNERABILITY":
                        dep_vulns += 1
                lang_extensions = {".py": "Python", ".js": "JavaScript", ".ts": "TypeScript", ".java": "Java",
                                   ".go": "Go", ".rb": "Ruby", ".php": "PHP", ".rs": "Rust", ".cs": "C#", ".swift": "Swift"}
                detected_langs = set()
                for f in findings:
                    fp = f.get("file_path") or f.get("endpoint", "")
                    ext = os.path.splitext(fp)[1]
                    if ext in lang_extensions:
                        detected_langs.add(lang_extensions[ext])
                frameworks = []
                for f in findings:
                    fp = (f.get("file_path") or f.get("endpoint", "")).lower()
                    if "flask" in fp or "django" in fp: frameworks.append("Django")
                    elif "express" in fp or "nestjs" in fp: frameworks.append("Express")
                    elif "spring" in fp: frameworks.append("Spring")
                    elif "laravel" in fp: frameworks.append("Laravel")
                    elif "rails" in fp: frameworks.append("Rails")
                    elif "fastapi" in fp: frameworks.append("FastAPI")
                ctx = ReconContext(
                    target_url=repo_url, scan_type="repo", repo_url=repo_url,
                    findings_count=findings_count, repo_clone_success=True,
                    languages_detected=sorted(detected_langs), vulnerability_types=sorted(set(vuln_types)),
                    severity_breakdown=severity_breakdown, critical_files=critical_files[:20],
                    frameworks_detected=list(set(frameworks)), has_hardcoded_secrets=has_secrets,
                    dependency_vulns_count=dep_vulns,
                )
                save_recon_context(self.engagement_id, ctx)
                logger.info(f"Saved repo recon context for {self.engagement_id}: {len(detected_langs)} languages, {len(vuln_types)} vuln types")
            except Exception as e:
                logger.warning(f"Failed to build repo recon context (non-fatal): {e}")

        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id, from_state="created", to_state=next_state,
            reason="Repository scan completed — auto-advancing to web scan",
        )
        return {"phase": "repo_scan", "status": "completed", "findings_count": findings_count,
                "next_state": next_state, "trace_id": get_trace_id()}

    def _get_org_id(self) -> str | None:
        """Get the org_id for the current engagement.

        Returns:
            org_id string, or None if unavailable
        """
        if self.engagement_repo:
            try:
                eng = self.engagement_repo.get_engagement(self.engagement_id)
                return str(eng.org_id) if eng else None
            except Exception:
                pass
        return None

    def _check_timeout(self):
        if self.start_time is None:
            return
        elapsed = time.time() - self.start_time
        if elapsed > HARD_TIMEOUT_SECONDS:
            self._log_timeout_event(elapsed)
            raise EngagementTimeoutError(
                f"Engagement {self.engagement_id} exceeded hard timeout "
                f"of {HARD_TIMEOUT_SECONDS} seconds (elapsed: {elapsed:.2f}s)"
            )

    def _get_scan_state(self) -> str:
        return "recon"

    def _log_timeout_event(self, elapsed_seconds: float):
        logger.warning(f"Engagement {self.engagement_id} exceeded hard timeout. "
                       f"Elapsed: {elapsed_seconds:.2f}s, Limit: {HARD_TIMEOUT_SECONDS}s")

    def get_elapsed_time(self) -> float:
        if self.start_time is None:
            return 0.0
        return time.time() - self.start_time

    def get_remaining_time(self) -> float:
        elapsed = self.get_elapsed_time()
        return max(0.0, HARD_TIMEOUT_SECONDS - elapsed)
