export enum Capability {
  WEB_RECON = "web_recon",
  PORT_SCANNING = "port_scanning",
  TECHNOLOGY_DETECTION = "technology_detection",
  CONTENT_DISCOVERY = "content_discovery",
  API_PROBING = "api_probing",
  AUTH_DETECTION = "auth_detection",
  CREDENTIAL_ANALYSIS = "credential_analysis",
  VULNERABILITY_SCANNING = "vulnerability_scanning",
  TEMPLATE_SCANNING = "template_scanning",
  BROWSER_VERIFICATION = "browser_verification",
  REPORT_GENERATION = "report_generation",
  SQLI_DETECTION = "sqli_detection",
  DATABASE_EXFILTRATION = "database_exfiltration",
  HTTP_PROBE = "http_probe",
  GRAPHQL_ASSESSMENT = "graphql_assessment",
  EXPRESS_CVE_SCAN = "express_cve_scan",
  API_DOCS_ANALYSIS = "api_docs_analysis",
  JWT_ANALYSIS = "jwt_analysis",
  SSRF_CHECK = "ssrf_check",

  SECURITY_ANALYSIS = "security_analysis",
  SECRET_DETECTION = "secret_detection",
  SAST = "sast",
  SCA = "sca",
  CVE_SCANNING = "cve_scanning",
  CLOUD_ENUM = "cloud_enum",
  S3_SCANNING = "s3_scanning",
}
