/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar-background)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        // Argus Brand Colors
        argus: {
          primary: "#6720FF",
          secondary: "#000000",
          tertiary: "#E6EAF4",
          neutral: "#FAF7FF",
        },
        // Extended Argus Palette
        surface: "#FAF7FF",
        "surface-bright": "#FAF7FF",
        "surface-dim": "#E8E5EF",
        "surface-container": "#F0EDF7",
        "surface-container-low": "#F5F2FA",
        "surface-container-high": "#EAE7F2",
        "surface-container-highest": "#E4E1EB",
        "surface-variant": "#E4E1EB",
        "surface-container-lowest": "#FFFFFF",
        "on-surface": "#1b1b21",
        "on-surface-variant": "#494457",
        "inverse-surface": "#303036",
        "inverse-on-surface": "#F2EFFF",
        outline: "#7A7489",
        "outline-variant": "#CAC3DA",
        "primary-container": "#6720FF",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#DDD1FF",
        "primary-fixed": "#E7DEFF",
        "primary-fixed-dim": "#CDBDFF",
        "on-primary-fixed": "#1F005F",
        "on-primary-fixed-variant": "#4E00D1",
        "inverse-primary": "#CDBDFF",
        "secondary-container": "#E2E2E2",
        "on-secondary": "#FFFFFF",
        "on-secondary-container": "#646464",
        "secondary-fixed": "#E2E2E2",
        "secondary-fixed-dim": "#C6C6C6",
        "on-secondary-fixed": "#1B1B1B",
        "on-secondary-fixed-variant": "#474747",
        "tertiary-container": "#595E66",
        "on-tertiary": "#FFFFFF",
        "on-tertiary-container": "#D3D7E1",
        "tertiary-fixed": "#DEE2EC",
        "tertiary-fixed-dim": "#C2C7D0",
        "on-tertiary-fixed": "#171C23",
        "on-tertiary-fixed-variant": "#42474F",
        error: "#BA1A1A",
        "error-container": "#FFDAD6",
        "on-error": "#FFFFFF",
        "on-error-container": "#93000A",
        "on-background": "#1B1B21",
        "surface-tint": "#6720FF",
        // Legacy aliases
        void: "var(--bg-void)",
        structural: "var(--border-structural)",
        "prism-cream": "var(--prism-cream)",
        "prism-muted": "var(--prism-muted)",
        "prism-cyan": "var(--prism-cyan)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        xl: "0.5rem",
        lg: "0.25rem",
        md: "0.125rem",
        sm: "0.125rem",
        xs: "0.125rem",
        full: "0.75rem",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        glow: "0 0 20px rgba(103, 32, 255, 0.2)",
        "glow-strong": "0 0 40px rgba(103, 32, 255, 0.3)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        progress: {
          "0%": { transform: "translateX(-100%)" },
          "50%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        shimmer: "shimmer 2s ease-in-out infinite",
        progress: "progress 1.5s ease-in-out infinite",
        "spin-slow": "spin-slow 20s linear infinite",
        "spin-slow-reverse": "spin-slow 15s linear infinite reverse",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};