"""
Agent Configuration Constants.
Everything overridable via environment variable.
"""
from config.constants import (
    LLM_AGENT_CONTEXT_MAX_TOKENS,
    LLM_AGENT_COST_PER_1K_INPUT,
    LLM_AGENT_COST_PER_1K_OUTPUT,
    LLM_AGENT_ENABLED,
    LLM_AGENT_MAX_COST_USD,
    LLM_AGENT_MAX_ITERATIONS,
    LLM_AGENT_MAX_RETRIES,
    LLM_AGENT_MAX_TOKENS_PLAN,
    LLM_AGENT_MAX_TOKENS_REPORT,
    LLM_AGENT_MAX_TOKENS_SYNTH,
    LLM_AGENT_MODEL,
    LLM_AGENT_TEMPERATURE,
    LLM_AGENT_TIMEOUT_SECONDS,
    LLM_AGENT_ZERO_FINDING_STOP,
)

# Re-export constants from config.constants for convenience
__all__ = [
    "LLM_AGENT_ENABLED",
    "LLM_AGENT_MODEL",
    "LLM_AGENT_MAX_ITERATIONS",
    "LLM_AGENT_TEMPERATURE",
    "LLM_AGENT_MAX_TOKENS_PLAN",
    "LLM_AGENT_MAX_TOKENS_SYNTH",
    "LLM_AGENT_MAX_TOKENS_REPORT",
    "LLM_AGENT_CONTEXT_MAX_TOKENS",
    "LLM_AGENT_MAX_COST_USD",
    "LLM_AGENT_COST_PER_1K_INPUT",
    "LLM_AGENT_COST_PER_1K_OUTPUT",
    "LLM_AGENT_TIMEOUT_SECONDS",
    "LLM_AGENT_MAX_RETRIES",
    "LLM_AGENT_ZERO_FINDING_STOP",
]
