"""
Bug Bounty Report Generator — Platform-specific vulnerability reports.

Copies Bug-Reaper's template system and adds an Argus adapter layer.
Maps Argus VulnerabilityFinding Pydantic model to Bug-Reaper's JSON input schema
and generates submission-ready reports for HackerOne, Bugcrowd, Intigriti, YesWeHack.

Pattern: Follows LLMReportGenerator and ComplianceReportGenerator patterns.
"""
import json
import logging
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

from utils.logging_utils import ScanLogger

logger = logging.getLogger(__name__)

# ═══════════════════════════════════════════════════════════════════════════════
# Bug-Reaper Platform Templates (copied from generate_report.py)
# ═══════════════════════════════════════════════════════════════════════════════

HACKERONE_TEMPLATE = """# {vuln_type_display}: {title}

## Summary
{summary}

## Impact
- **Security property violated:** {cia_impact}
- **Attacker achieves:** {attacker_achieves}
- **Who is affected:** {affected_scope}
- **Worst case:** {worst_case}

## Steps to Reproduce

{steps}

## Proof of Concept

```
{poc}
```

## Root Cause
{root_cause}

## Remediation
{remediation}

---
*Generated by Argus Bug Bounty Report | {date}*
"""

BUGCROWD_TEMPLATE = """## Summary
{summary}

## Technical Details
**Vulnerable Endpoint:** `{endpoint}`
**Input Vector:** {input_vector}
**Missing Control:** {missing_control}
**Why Exploitable:** {why_exploitable}

## Steps to Reproduce

{steps}

## Proof of Concept

```
{poc}
```

## Impact
- **Attacker capability:** {attacker_achieves}
- **Data exposure:** {data_exposure}
- **Privilege escalation:** {priv_escalation}
- **Business risk:** {business_risk}

## CWE Classification
**{cwe}**
{cwe_reason}

## Remediation
{remediation}

---
*Generated by Argus Bug Bounty Report | {date}*
"""

INTIGRITI_TEMPLATE = """### Description
{summary}

*Affected Component:* `{endpoint}`

### Technical Analysis

**How the vulnerability works:**
{how_it_works}

**Why the security control fails:**
{why_control_fails}

**Trust boundary violated:**
{trust_boundary}

### Steps to Reproduce

{steps}

### Proof of Concept

```
{poc}
```

### Impact

**Data exposure / Access escalation:**
{attacker_achieves}

**Attack preconditions:**
{prerequisites}

**Realistic abuse scenario:**
{realistic_scenario}

### Recommendation
{remediation}

---
*Generated by Argus Bug Bounty Report | {date}*
"""

YESWEHACK_TEMPLATE = """# Vulnerability Overview
{summary}

# Affected Endpoint / Component
**Endpoint:** `{endpoint}`
**Component:** {component}

# Technical Details

**Root cause:**
{root_cause}

**Exploit mechanism:**
{how_it_works}

**Security assumption broken:**
{trust_boundary}

# Steps to Reproduce

{steps}

# Proof of Concept

```
{poc}
```

# Security Impact

**Confidentiality:** {confidentiality}
**Integrity:** {integrity}
**Availability:** {availability}

**Practical attack scenario:**
{realistic_scenario}

**Worst-case business outcome:**
{worst_case}

# Suggested Fix
{remediation}

---
*Generated by Argus Bug Bounty Report | {date}*
"""

# ═══════════════════════════════════════════════════════════════════════════════
# Vulnerability Type Metadata
# ═══════════════════════════════════════════════════════════════════════════════

VULN_META = {
    "xss": {
        "display": "Cross-Site Scripting (XSS)",
        "cwe": "CWE-79: Improper Neutralization of Input During Web Page Generation",
        "default_cia": "Confidentiality (session tokens), Integrity (page content)",
    },
    "sqli": {
        "display": "SQL Injection",
        "cwe": "CWE-89: Improper Neutralization of Special Elements Used in SQL Command",
        "default_cia": "Confidentiality (database data), Integrity (data modification)",
    },
    "ssrf": {
        "display": "Server-Side Request Forgery (SSRF)",
        "cwe": "CWE-918: Server-Side Request Forgery",
        "default_cia": "Confidentiality (internal service access, cloud credentials)",
    },
    "idor": {
        "display": "Insecure Direct Object Reference (IDOR)",
        "cwe": "CWE-639: Authorization Bypass Through User-Controlled Key",
        "default_cia": "Confidentiality (other users' data), Integrity (unauthorized modification)",
    },
    "auth": {
        "display": "Authentication/Authorization Bypass",
        "cwe": "CWE-287: Improper Authentication",
        "default_cia": "Confidentiality, Integrity (full account compromise)",
    },
    "biz-logic": {
        "display": "Business Logic Vulnerability",
        "cwe": "CWE-840: Business Logic Errors",
        "default_cia": "Integrity (price manipulation, workflow bypass)",
    },
    "rce": {
        "display": "Remote Code Execution (RCE)",
        "cwe": "CWE-78: OS Command Injection / CWE-94: Code Injection",
        "default_cia": "Confidentiality, Integrity, Availability (full server compromise)",
    },
    "lfi": {
        "display": "Local File Inclusion (LFI) / Path Traversal",
        "cwe": "CWE-22: Improper Limitation of a Pathname to a Restricted Directory",
        "default_cia": "Confidentiality (file system access, credentials)",
    },
    "open-redirect": {
        "display": "Open Redirect",
        "cwe": "CWE-601: URL Redirection to Untrusted Site",
        "default_cia": "Integrity (trust abuse), potential phishing chain",
    },
    "ssti": {
        "display": "Server-Side Template Injection (SSTI)",
        "cwe": "CWE-94: Improper Control of Generation of Code",
        "default_cia": "Confidentiality, Integrity, Availability (RCE potential)",
    },
    "xxe": {
        "display": "XML External Entity Injection (XXE)",
        "cwe": "CWE-611: Improper Restriction of XML External Entity Reference",
        "default_cia": "Confidentiality (file read, SSRF via XML)",
    },
    "cors": {
        "display": "CORS Misconfiguration",
        "cwe": "CWE-346: Origin Validation Error",
        "default_cia": "Confidentiality (cross-origin credential and data theft)",
    },
    "csrf": {
        "display": "Cross-Site Request Forgery (CSRF)",
        "cwe": "CWE-352: Cross-Site Request Forgery",
        "default_cia": "Integrity (unauthorized state change on behalf of victim)",
    },
    "subdomain-takeover": {
        "display": "Subdomain Takeover",
        "cwe": "CWE-350: Reliance on Reverse DNS Resolution",
        "default_cia": "Integrity (attacker controls trusted domain), Confidentiality (cookie theft)",
    },
    "prototype-pollution": {
        "display": "Prototype Pollution",
        "cwe": "CWE-1321: Improperly Controlled Modification of Object Prototype Attributes",
        "default_cia": "Integrity (property injection), potential RCE via gadget chains",
    },
    "http-smuggling": {
        "display": "HTTP Request Smuggling",
        "cwe": "CWE-444: Inconsistent Interpretation of HTTP Requests",
        "default_cia": "Confidentiality (capture victim requests), Integrity (bypass access controls)",
    },
    "api-graphql": {
        "display": "API / GraphQL Security Issue",
        "cwe": "CWE-285: Improper Authorization",
        "default_cia": "Confidentiality (unauthorized data access), Integrity (unauthorized modification)",
    },
    "nosqli": {
        "display": "NoSQL Injection",
        "cwe": "CWE-943: Improper Neutralization of Special Elements in Data Query Logic",
        "default_cia": "Confidentiality (data extraction), Authentication Bypass (full account compromise)",
    },
}

# ═══════════════════════════════════════════════════════════════════════════════
# Argus Finding Type to Bug-Reaper Vulnerability Type Mapping
# ═══════════════════════════════════════════════════════════════════════════════

ARGUS_TYPE_TO_BUGREAPER = {
    "XSS": "xss",
    "REFLECTED_XSS": "xss",
    "STORED_XSS": "xss",
    "DOM_XSS": "xss",
    "BLIND_XSS": "xss",
    "SQL_INJECTION": "sqli",
    "BLIND_SQLI": "sqli",
    "TIME_BASED_SQLI": "sqli",
    "ERROR_BASED_SQLI": "sqli",
    "SSRF": "ssrf",
    "IDOR": "idor",
    "BOLA": "idor",
    "BROKEN_AUTHENTICATION": "auth",
    "BROKEN_AUTH": "auth",
    "JWT_WEAKNESS": "auth",
    "JWT_ATTACK": "auth",
    "AUTH_BYPASS": "auth",
    "SSTI": "ssti",
    "PATH_TRAVERSAL": "lfi",
    "LFI": "lfi",
    "DIRECTORY_TRAVERSAL": "lfi",
    "XXE": "xxe",
    "CORS_MISCONFIGURATION": "cors",
    "CORS": "cors",
    "CSRF": "csrf",
    "RCE": "rce",
    "COMMAND_INJECTION": "rce",
    "OPEN_REDIRECT": "open-redirect",
    "SUBDOMAIN_TAKEOVER": "subdomain-takeover",
    "PROTOTYPE_POLLUTION": "prototype-pollution",
    "HTTP_SMUGGLING": "http-smuggling",
    "API_VULNERABILITY": "api-graphql",
    "API_GRAPHQL": "api-graphql",
    "GRAPHQL": "api-graphql",
    "NOSQL_INJECTION": "nosqli",
    "NOSQLI": "nosqli",
    "BUSINESS_LOGIC": "biz-logic",
    "BIZ_LOGIC": "biz-logic",
    "RACE_CONDITION": "biz-logic",
}

TRUST_BOUNDARY_MAP: dict[str, str] = {
    "idor": "Regular user → Another user's private data (missing authorization check)",
    "auth": "User authentication → Full account compromise (bypassed auth mechanism)",
    "ssrf": "User input → Server-side internal network request (no URL validation)",
    "xss": "User input → HTML/JS execution in victim's browser (no output encoding)",
    "sqli": "User input → SQL query execution on database (no parameterization)",
    "rce": "User input → OS command execution on server (no input sanitization)",
    "cors": "Attacker origin → Cross-origin authenticated API access (no origin validation)",
    "lfi": "User input → Server file system read (no path validation)",
    "xxe": "XML input → Server file read / SSRF (DTD processing enabled)",
    "ssti": "User input → Server-side template evaluation (no template sandboxing)",
    "subdomain-takeover": "Attacker → Control of trusted subdomain (dangling DNS record)",
    "open-redirect": "User input → Redirect to attacker-controlled URL (no URL allowlist)",
    "csrf": "Attacker website → Authenticated state change (missing CSRF token)",
    "api-graphql": "Unauthenticated user → Unauthorized API data access (no auth check)",
    "http-smuggling": "Attacker request → Poisoned proxy interpretation (CL/TE confusion)",
    "prototype-pollution": "User input → Object prototype contamination (no __proto__ filtering)",
    "nosqli": "User input → MongoDB operator injection (no type checking)",
    "biz-logic": "User action → Unauthorized business outcome (workflow bypass)",
}

IMPACT_STATEMENT_MAP: dict[str, str] = {
    "IDOR": "Read, modify, or delete any user's private data without authorization",
    "BROKEN_AUTHENTICATION": "Bypass authentication or escalate privileges without valid credentials",
    "BROKEN_AUTH": "Bypass authentication or escalate privileges without valid credentials",
    "SSRF": "Access internal services, cloud metadata, or exfiltrate cloud credentials",
    "XSS": "Execute arbitrary JavaScript in victim's browser context, steal session tokens",
    "SQL_INJECTION": "Extract database contents, potentially modify or delete records",
    "RCE": "Execute arbitrary OS commands on the server",
    "CORS_MISCONFIGURATION": "Read victim's authenticated API responses from attacker-controlled origin",
    "LFI": "Read arbitrary files from the server filesystem including credentials",
    "SSTI": "Execute arbitrary code on the server via template injection",
    "XXE": "Read local files or achieve SSRF via XML external entity injection",
    "CSRF": "Perform unauthorized state-changing actions on behalf of a victim",
    "SUBDOMAIN_TAKEOVER": "Host arbitrary content under a trusted subdomain",
    "OPEN_REDIRECT": "Redirect users to malicious sites, enabling phishing attacks",
    "NOSQL_INJECTION": "Bypass authentication or extract data via MongoDB operator injection",
    "PROTOTYPE_POLLUTION": "Inject properties into object prototypes, potentially leading to RCE",
    "HTTP_SMUGGLING": "Bypass security controls by smuggling requests through proxy",
    "API_VULNERABILITY": "Access unauthorized API data or perform unauthorized API actions",
    "BUSINESS_LOGIC": "Manipulate business workflows for unauthorized financial or data gain",
}

SEVERITY_TO_WORST_CASE: dict[str, str] = {
    "CRITICAL": "Full application or infrastructure compromise — unauthenticated RCE or account takeover",
    "HIGH": "Unauthorized access to sensitive user data, privilege escalation, or account takeover",
    "MEDIUM": "Limited unauthorized data access or security control bypass requiring victim interaction",
    "LOW": "Minor information disclosure or theoretical attack path with limited impact",
}


# ═══════════════════════════════════════════════════════════════════════════════
# Formatting Helpers
# ═══════════════════════════════════════════════════════════════════════════════

def format_steps(steps_input: Any) -> str:
    """Format steps as numbered markdown list."""
    if isinstance(steps_input, list):
        return "\n".join(f"{i+1}. {step}" for i, step in enumerate(steps_input))
    elif isinstance(steps_input, str):
        lines = [line.strip() for line in steps_input.strip().split("\n") if line.strip()]
        formatted = []
        for i, line in enumerate(lines):
            if re.match(r"^\d+\.", line):
                formatted.append(line)
            else:
                formatted.append(f"{i+1}. {line}")
        return "\n".join(formatted)
    return "1. [Steps to reproduce not provided]"


def get_field(data: dict, field: str, default: str = "[Not provided]") -> str:
    """Safely get a field value with a default."""
    return data.get(field, default) or default


# ═══════════════════════════════════════════════════════════════════════════════
# Bug-Reaper Generator Functions (ported from generate_report.py)
# ═══════════════════════════════════════════════════════════════════════════════

def generate_hackerone(data: dict, vuln_type: str) -> str:
    """Generate HackerOne-format bug bounty report."""
    meta = VULN_META.get(vuln_type, {"display": vuln_type.upper(), "cwe": "", "default_cia": ""})
    return HACKERONE_TEMPLATE.format(
        vuln_type_display=meta["display"],
        title=get_field(data, "title"),
        summary=get_field(data, "summary"),
        cia_impact=get_field(data, "cia_impact", meta["default_cia"]),
        attacker_achieves=get_field(data, "attacker_achieves"),
        affected_scope=get_field(data, "affected_scope", "All authenticated users"),
        worst_case=get_field(data, "worst_case"),
        steps=format_steps(get_field(data, "steps")),
        poc=get_field(data, "poc"),
        root_cause=get_field(data, "root_cause"),
        remediation=get_field(data, "remediation"),
        date=datetime.now().strftime("%Y-%m-%d"),
    )


def generate_bugcrowd(data: dict, vuln_type: str) -> str:
    """Generate Bugcrowd-format bug bounty report."""
    meta = VULN_META.get(vuln_type, {"display": vuln_type.upper(), "cwe": "CWE-XXX", "default_cia": ""})
    return BUGCROWD_TEMPLATE.format(
        summary=get_field(data, "summary"),
        endpoint=get_field(data, "endpoint"),
        input_vector=get_field(data, "input_vector", "[User-controlled parameter]"),
        missing_control=get_field(data, "missing_control", "[Missing security control]"),
        why_exploitable=get_field(data, "root_cause"),
        steps=format_steps(get_field(data, "steps")),
        poc=get_field(data, "poc"),
        attacker_achieves=get_field(data, "attacker_achieves"),
        data_exposure=get_field(data, "data_exposure", get_field(data, "attacker_achieves")),
        priv_escalation=get_field(data, "priv_escalation", "N/A"),
        business_risk=get_field(data, "business_risk", get_field(data, "worst_case")),
        cwe=meta["cwe"],
        cwe_reason=(
            f"This vulnerability fits {meta['cwe'].split(':')[0]} because the application "
            f"fails to properly control access to {get_field(data, 'endpoint', 'the affected resource')}."
        ),
        remediation=get_field(data, "remediation"),
        date=datetime.now().strftime("%Y-%m-%d"),
    )


def generate_intigriti(data: dict, vuln_type: str) -> str:
    """Generate Intigriti-format bug bounty report."""
    return INTIGRITI_TEMPLATE.format(
        summary=get_field(data, "summary"),
        endpoint=get_field(data, "endpoint"),
        how_it_works=get_field(data, "root_cause"),
        why_control_fails=get_field(
            data, "missing_control",
            "[Security control that should prevent this is absent or bypassed]"
        ),
        trust_boundary=get_field(data, "trust_boundary", "[Trust boundary violated]"),
        steps=format_steps(get_field(data, "steps")),
        poc=get_field(data, "poc"),
        attacker_achieves=get_field(data, "attacker_achieves"),
        prerequisites=get_field(data, "prerequisites", "Standard user account"),
        realistic_scenario=get_field(data, "realistic_scenario",
                                     get_field(data, "attacker_achieves")),
        remediation=get_field(data, "remediation"),
        date=datetime.now().strftime("%Y-%m-%d"),
    )


def generate_yeswehack(data: dict, vuln_type: str) -> str:
    """Generate YesWeHack-format bug bounty report."""
    cia = get_field(data, "cia_impact", "")
    conf = "Impacted" if ("confidentiality" in cia.lower() or "data" in cia.lower()) else "Not impacted"
    integ = "Impacted" if ("integrity" in cia.lower() or "modif" in cia.lower()) else "Not impacted"
    avail = "Impacted" if ("availability" in cia.lower() or "dos" in cia.lower()) else "Not impacted"

    return YESWEHACK_TEMPLATE.format(
        summary=get_field(data, "summary"),
        endpoint=get_field(data, "endpoint"),
        component=get_field(data, "component", "[Affected component]"),
        root_cause=get_field(data, "root_cause"),
        how_it_works=get_field(data, "root_cause"),
        trust_boundary=get_field(data, "trust_boundary", "[Trust boundary violated]"),
        steps=format_steps(get_field(data, "steps")),
        poc=get_field(data, "poc"),
        confidentiality=get_field(data, "confidentiality", conf),
        integrity=get_field(data, "integrity", integ),
        availability=get_field(data, "availability", avail),
        realistic_scenario=get_field(data, "realistic_scenario",
                                     get_field(data, "attacker_achieves")),
        worst_case=get_field(data, "worst_case"),
        remediation=get_field(data, "remediation"),
        date=datetime.now().strftime("%Y-%m-%d"),
    )


GENERATORS: dict[str, Any] = {
    "hackerone": generate_hackerone,
    "bugcrowd": generate_bugcrowd,
    "intigriti": generate_intigriti,
    "yeswehack": generate_yeswehack,
}


# ═══════════════════════════════════════════════════════════════════════════════
# Argus Finding Adapter
# ═══════════════════════════════════════════════════════════════════════════════

class ArgusFindingAdapter:
    """
    Converts Argus VulnerabilityFinding dicts to Bug-Reaper's expected JSON schema.

    Bug-Reaper expects:
        title, endpoint, summary, steps, poc, root_cause, remediation,
        attacker_achieves, trust_boundary, cia_impact, worst_case, ...
    """

    @staticmethod
    def adapt(argus_finding: dict, vuln_type: str, engagement: dict | None = None) -> dict:
        """Convert an Argus finding dict to Bug-Reaper's JSON input schema."""
        evidence = argus_finding.get("evidence") or {}
        type_key = argus_finding.get("type", "").upper()
        severity = argus_finding.get("severity", "MEDIUM").upper()

        # Extract PoC from whatever evidence we have
        poc = (
            evidence.get("request")
            or evidence.get("payload")
            or evidence.get("raw_request")
            or evidence.get("response", "")[:500]
            or json.dumps(evidence, indent=2)[:500]
            or "[PoC captured during scan — see evidence in Argus platform]"
        )

        # Extract reproduction steps
        steps = (
            argus_finding.get("repro_steps")
            or evidence.get("repro_steps")
            or evidence.get("steps")
            or [
                f"Navigate to {argus_finding.get('endpoint', 'the vulnerable endpoint')}",
                "Send the request as shown in the PoC below",
                "Observe the vulnerability as described",
            ]
        )

        return {
            "title": f"{argus_finding.get('type', 'Vulnerability').replace('_', ' ').title()} "
                     f"on {argus_finding.get('endpoint', 'unknown endpoint')}",
            "endpoint": argus_finding.get("endpoint", "[Endpoint not specified]"),
            "summary": (
                argus_finding.get("description")
                or f"A {severity.lower()} severity {argus_finding.get('type', 'vulnerability').lower()} "
                   f"was detected at {argus_finding.get('endpoint', 'the target endpoint')} "
                   f"by {argus_finding.get('source_tool', 'automated scanner')}."
            ),
            "steps": steps,
            "poc": poc,
            "root_cause": (
                evidence.get("root_cause")
                or argus_finding.get("remediation")
                or f"Missing security control on {argus_finding.get('endpoint', 'the endpoint')} "
                   f"allowing {argus_finding.get('type', 'vulnerability').lower()}"
            ),
            "remediation": (
                argus_finding.get("remediation")
                or f"Implement proper validation and authorization checks "
                   f"for {argus_finding.get('type', 'this vulnerability class').lower()}"
            ),
            "attacker_achieves": IMPACT_STATEMENT_MAP.get(
                type_key,
                f"Unauthorized access to protected resources via {argus_finding.get('type', 'vulnerability')}"
            ),
            "trust_boundary": TRUST_BOUNDARY_MAP.get(
                vuln_type,
                "[Trust boundary violated — authorization or validation bypass detected]"
            ),
            "cia_impact": VULN_META.get(vuln_type, {}).get("default_cia", "Confidentiality, Integrity"),
            "worst_case": SEVERITY_TO_WORST_CASE.get(severity, "Security control bypass"),
            "affected_scope": (
                f"Users of {engagement.get('target_url', 'the application')}"
                if engagement
                else "Application users"
            ),
            "missing_control": (
                f"Missing {'authorization check' if vuln_type == 'idor' else 'input validation'} "
                f"on {argus_finding.get('endpoint', 'the endpoint')}"
            ),
        }


# ═══════════════════════════════════════════════════════════════════════════════
# Bug Bounty Report Generator
# ═══════════════════════════════════════════════════════════════════════════════

class BugBountyReportGenerator:
    """
    Generates platform-specific bug bounty reports from Argus findings.

    Follows the same pattern as LLMReportGenerator and ComplianceReportGenerator.
    Uses Bug-Reaper's template system (ported) for platform formatting.

    Usage:
        generator = BugBountyReportGenerator()
        md = generator.generate(findings, platform="hackerone", engagement=engagement_data)
    """

    SUPPORTED_PLATFORMS = list(GENERATORS.keys())

    def __init__(self):
        self.adapter = ArgusFindingAdapter()

    def generate(
        self,
        findings: list[dict],
        platform: str,
        engagement: dict | None = None,
        min_confidence: float = 0.65,
    ) -> str:
        """
        Generate a platform-specific bug bounty report from Argus findings.

        Applies Bug-Reaper's audit rules:
        - Only findings with confidence >= min_confidence
        - Only findings with severity CRITICAL, HIGH, or MEDIUM
        - Excludes findings flagged as false positives

        Args:
            findings: List of Argus finding dicts (VulnerabilityFinding model)
            platform: Target platform ('hackerone', 'bugcrowd', 'intigriti', 'yeswehack')
            engagement: Optional engagement dict with metadata
            min_confidence: Minimum confidence threshold (default 0.65 = Bug-Reaper standard)

        Returns:
            Markdown string with platform-formatted report(s)
        """
        slog = ScanLogger("bugbounty_report_generator")

        platform = platform.lower()
        if platform not in self.SUPPORTED_PLATFORMS:
            raise ValueError(
                f"Unsupported platform: {platform}. "
                f"Supported: {', '.join(self.SUPPORTED_PLATFORMS)}"
            )

        slog.phase_header("Bug Bounty Report", platform)
        slog.info(f"Processing {len(findings)} findings (min_confidence={min_confidence})")

        # Apply Bug-Reaper audit rules: filter findings by quality
        reportable = self._filter_findings(findings, min_confidence)
        slog.info(f"{len(reportable)}/{len(findings)} findings reportable after filtering")

        if not reportable:
            slog.info("No reportable vulnerabilities — generating empty report")
            return (
                f"# Bug Bounty Report — {platform.upper()}\n\n"
                f"**No reportable vulnerabilities identified.**\n\n"
                f"Findings that were evaluated:\n"
                + "\n".join(
                    f"- {f.get('type', 'Unknown')} at {f.get('endpoint', '?')} "
                    f"(confidence: {f.get('confidence', 0):.2f}, "
                    f"severity: {f.get('severity', '?')}) "
                    f"— {'below confidence threshold' if f.get('confidence', 0) < min_confidence else 'below Medium severity'}"
                    for f in findings
                )
                if findings
                else "No findings found for this engagement."
            )

        # Generate platform-specific reports
        reports = []
        generator_fn = GENERATORS[platform]

        for finding in reportable:
            vuln_type = self._map_type(finding)
            finding_data = self.adapter.adapt(finding, vuln_type, engagement)
            try:
                report_md = generator_fn(finding_data, vuln_type)
                reports.append(report_md)
            except Exception as e:
                slog.warn(f"Failed to generate report for finding {finding.get('id', '?')}: {e}")
                logger.warning(f"Failed to generate report for finding {finding.get('id', '?')}: {e}")
                continue

        # Wrap with header
        header = (
            f"# Argus Bug Bounty Report — {platform.upper()}\n"
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}\n"
            f"**Findings:** {len(reports)} reportable\n"
            f"**Target:** {engagement.get('target_url', 'N/A') if engagement else 'N/A'}\n\n"
            f"---\n\n"
        )

        slog.tool_complete("report_generation", platform=platform, reports=len(reports))
        return header + "\n\n---\n\n".join(reports)

    def _filter_findings(self, findings: list[dict], min_confidence: float) -> list[dict]:
        """
        Apply Bug-Reaper's audit rules:
        1. Minimum confidence threshold (0.65 = Probable)
        2. Minimum severity: Medium
        3. Exclude false positives
        4. Exclude unvalidated findings (requires_validation with no validation)
        """
        reportable = []
        rejected = []

        for f in findings:
            # Check false positive flag
            if f.get("false_positive") or f.get("fp_assessment", {}).get("verdict") in (
                "false_positive", "likely_false_positive"
            ):
                rejected.append(f)
                continue

            # Check severity
            severity = str(f.get("severity", "")).upper()
            if severity not in ("CRITICAL", "HIGH", "MEDIUM"):
                rejected.append(f)
                continue

            # Check confidence
            confidence = float(f.get("confidence", 0))
            if confidence < min_confidence:
                rejected.append(f)
                continue

            reportable.append(f)

        return reportable

    def _map_type(self, finding: dict) -> str:
        """Map Argus finding type to Bug-Reaper vulnerability type."""
        type_str = str(finding.get("type", "")).upper()
        mapped = ARGUS_TYPE_TO_BUGREAPER.get(type_str, "api-graphql")

        # Fallback: check tags for hints
        if mapped == "api-graphql":
            tags = finding.get("tags", [])
            for tag in tags:
                if tag in ARGUS_TYPE_TO_BUGREAPER:
                    return ARGUS_TYPE_TO_BUGREAPER[tag]

        return mapped

    def list_supported_platforms(self) -> list[str]:
        """List all supported bug bounty platforms."""
        return self.SUPPORTED_PLATFORMS

    def list_supported_types(self) -> list[str]:
        """List all supported vulnerability types."""
        return list(VULN_META.keys())


# ═══════════════════════════════════════════════════════════════════════════════
# CLI Entry Point
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    """
    CLI entry point for generating bug bounty reports.

    Usage:
        python -m tools.bugbounty_report_generator \\
            --findings findings.json \\
            --platform hackerone \\
            --target-url https://example.com \\
            --output report.md
    """
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate Bug Bounty report from Argus findings"
    )
    parser.add_argument("--findings", required=True,
                        help="Path to JSON file with findings array")
    parser.add_argument("--platform", required=True,
                        choices=list(GENERATORS.keys()),
                        help="Target bug bounty platform")
    parser.add_argument("--target-url", default="",
                        help="Target URL for the engagement")
    parser.add_argument("--output", default="",
                        help="Output file path (default: stdout)")
    parser.add_argument("--min-confidence", type=float, default=0.65,
                        help="Minimum confidence threshold (default: 0.65)")

    args = parser.parse_args()

    # Load findings
    findings_path = Path(args.findings)
    if not findings_path.exists():
        print(f"Error: Findings file not found: {args.findings}", file=sys.stderr)
        sys.exit(1)

    try:
        with open(findings_path) as f:
            findings = json.load(f)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in findings file: {e}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(findings, list):
        findings = [findings]

    # Build engagement context
    engagement = {}
    if args.target_url:
        engagement["target_url"] = args.target_url

    # Generate report
    generator = BugBountyReportGenerator()
    try:
        report_md = generator.generate(
            findings=findings,
            platform=args.platform,
            engagement=engagement,
            min_confidence=args.min_confidence,
        )
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Output
    if args.output:
        output_path = Path(args.output)
        output_path.write_text(report_md, encoding="utf-8")
        print(f"Report saved to {args.output}")
        print(f"Platform: {args.platform.upper()}")
        print(f"Findings in report: {findings_count(report_md)}")
    else:
        print(report_md)


def findings_count(report_md: str) -> int:
    """Count number of individual finding reports in the markdown."""
    return max(1, report_md.count("## Summary") + report_md.count("## Technical Details"))


if __name__ == "__main__":
    main()
