"""Init command for the Argus CLI."""

from __future__ import annotations

import json
import logging
import os
import tempfile
import time
import uuid
from pathlib import Path
from typing import Any

import cli._local_mode as local_mode

logger = logging.getLogger("cli.cmd")


def cmd_init(args: argparse.Namespace) -> int:
    """Initialize Argus configuration: generate encryption keys and .env file.

    Checks for:
    1. Existing .env file (--force to overwrite)
    2. Generates AUTH_CHECKPOINT_KEY (Fernet) if missing
    3. Generates SETTINGS_ENCRYPTION_KEY (Fernet) if missing
    4. Creates local SQLite database directory
    5. Runs preflight check to verify setup

    Returns:
        0 on success, 1 on failure.
    """
    force = getattr(args, "force", False)
    exit_code = 0
    generated: list[str] = []

    # ── Determine .env path ──
    # Walk up from the script directory to find the project root (.env.example location)
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent  # parent of argus-workers/
    env_path = project_root / ".env"

    # Also check if there's an .env in the workers dir
    workers_env = script_dir / ".env"
    env_candidates = [env_path, workers_env]

    # ── Check existing .env ──
    existing_env = None
    for candidate in env_candidates:
        if candidate.exists():
            existing_env = candidate
            break

    if existing_env and not force:
        print(f"  .env already exists at: {existing_env}")
        print(f"  Use --force to overwrite (existing file will be backed up).")
        exit_code = 1
    else:
        # ── Generate encryption keys ──
        try:
            from cryptography.fernet import Fernet

            auth_key = Fernet.generate_key().decode()
            settings_key = Fernet.generate_key().decode()
            generated = ["AUTH_CHECKPOINT_KEY", "SETTINGS_ENCRYPTION_KEY"]

            print(f"  Generated AUTH_CHECKPOINT_KEY:    {auth_key}")
            print(f"  Generated SETTINGS_ENCRYPTION_KEY: {settings_key}")

        except ImportError:
            logger.error("cryptography package not installed — cannot generate Fernet keys")
            print("Error: cryptography package is required. Install with: pip install cryptography")
            return 1

        # ── Write .env ──
        # Use the project root .env path by default
        target_env = env_path

        # Backup existing file if overwriting
        if existing_env:
            backup = existing_env.with_suffix(".env.bak")
            import shutil
            shutil.copy2(existing_env, backup)
            print(f"  Backed up existing .env to: {backup}")
            target_env = existing_env

        try:
            from datetime import datetime

            if existing_env:
                # Read existing content, strip old key lines, add new keys.
                # This preserves ALL other config (DATABASE_URL, LLM_API_KEY, etc.).
                existing_lines = existing_env.read_text(encoding="utf-8").splitlines()
                filtered = [
                    line for line in existing_lines
                    if not line.startswith(("AUTH_CHECKPOINT_KEY=", "SETTINGS_ENCRYPTION_KEY="))
                ]
                # Add header for new keys
                filtered.append("")
                filtered.append(f"# Updated by `argus init` on {datetime.now().isoformat()}")
                filtered.append("# -- Encryption Keys -------------------------------------------")
                filtered.append(f"AUTH_CHECKPOINT_KEY={auth_key}")
                filtered.append(f"SETTINGS_ENCRYPTION_KEY={settings_key}")
                target_env.write_text("\n".join(filtered) + "\n", encoding="utf-8")
            else:
                # No existing .env — create a fresh one
                with open(target_env, "w", encoding="utf-8") as f:
                    f.write("# Argus Environment Configuration (auto-generated by `argus init`)\n")
                    f.write(f"# Generated: {datetime.now().isoformat()}\n")
                    f.write("# ---------------------------------------------------------------\n\n")
                    f.write("# -- Encryption Keys -------------------------------------------\n")
                    f.write(f"AUTH_CHECKPOINT_KEY={auth_key}\n")
                    f.write(f"SETTINGS_ENCRYPTION_KEY={settings_key}\n")

            print(f"  Wrote config to: {target_env}")

            # Load the new env vars into the current process
            os.environ["AUTH_CHECKPOINT_KEY"] = auth_key
            os.environ["SETTINGS_ENCRYPTION_KEY"] = settings_key

        except OSError as e:
            logger.error("Failed to write .env file: %s", e)
            print(f"Error: Could not write .env file: {e}")
            return 1

    # ── Create local SQLite database directory ──
    db_dir = Path.home() / ".argus" / "assessments"
    try:
        db_dir.mkdir(parents=True, exist_ok=True)
        print(f"  Local database directory: {db_dir}")
    except OSError as e:
        logger.warning("Could not create database directory: %s", e)
        print(f"  Warning: Could not create {db_dir}: {e}")

    # ── Run preflight check ──
    print()
    try:
        from runtime.preflight import run_preflight, display_preflight_report

        preflight = run_preflight()
        print(display_preflight_report(preflight, verbose=True))

        if preflight.has_errors():
            print("  Some preflight checks failed. Review the issues above.")
            exit_code = 1
        elif preflight.has_warnings():
            print("  All checks passed with warnings. Review the issues above.")
        else:
            print("  All checks passed!")
    except ImportError as e:
        logger.debug("Preflight module not available: %s", e)
        print("  (Preflight check module not available — skipping)")
    except Exception as e:
        logger.warning("Preflight check failed: %s", e)
        print(f"  (Preflight check failed: {e})")

    # ── Summary ──
    print()
    if generated:
        print(f"  [OK] Generated and saved: {', '.join(generated)}")
        print(f"  [INFO] Restart any running workers to pick up the new keys.")
    if exit_code == 0:
        print("  [OK] Init complete.")
    else:
        print(f"  [WARN] Init completed with issues.")

    return exit_code


