"""
Orchestrator - Workflow executor ONLY (no decision-making)
Executes actions generated by Intelligence Engine

Requirements: 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 21.1, 21.2, 31.2, 31.3
"""
import logging
import time
from typing import Dict, List, Optional
import os

logger = logging.getLogger(__name__)

from tracing import (
    TracingManager,
    TraceContext,
    get_trace_id,
    StructuredLogger,
    ExecutionSpan,
)
from websocket_events import (
    WebSocketEventPublisher,
    get_websocket_publisher,
)
from tools.tool_runner import ToolRunner
from tools.web_scanner import WebScanner
from parsers.parser import Parser
from parsers.normalizer import FindingNormalizer
from database.repositories.finding_repository import FindingRepository
from database.repositories.engagement_repository import EngagementRepository


class EngagementTimeoutError(Exception):
    """Raised when engagement exceeds hard timeout"""
    pass


class Orchestrator:
    """
    Workflow execution engine.
    Executes actions generated by Intelligence Engine without making decisions.
    """
    
    # Hard timeout: 3600 seconds (1 hour)
    HARD_TIMEOUT_SECONDS = 3600
    
    def __init__(self, engagement_id: str, trace_id: str = None):
        """
        Initialize Orchestrator
        
        Args:
            engagement_id: Engagement ID
            trace_id: Optional trace_id for distributed tracing
        """
        self.engagement_id = engagement_id
        self.start_time = None
        self.trace_id = trace_id
        
        # Initialize tracing components
        db_conn = os.getenv("DATABASE_URL")
        self.tracing_manager = TracingManager(db_conn)
        self.logger = StructuredLogger(db_conn)
        self.span_recorder = ExecutionSpan(db_conn)
        
        # Initialize WebSocket event publisher
        self.ws_publisher = get_websocket_publisher()
        
        # Initialize execution components
        self.tool_runner = ToolRunner(connection_string=db_conn)
        self.parser = Parser(connection_string=db_conn)
        self.normalizer = FindingNormalizer()
        self.finding_repo = FindingRepository(db_conn) if db_conn else None
        self.engagement_repo = EngagementRepository(db_conn) if db_conn else None
    
    def run(self, job: Dict) -> Dict:
        """
        Execute job workflow
        
        Args:
            job: Job dictionary with type and parameters
            
        Returns:
            Execution result
            
        Raises:
            EngagementTimeoutError: If hard timeout exceeded
        """
        # Start timer
        if self.start_time is None:
            self.start_time = time.time()
        
        # Check hard timeout
        self._check_timeout()
        
        # Route to appropriate workflow
        job_type = job.get("type")
        
        # Log orchestrator step with trace_id
        with self.span_recorder.span(ExecutionSpan.SPAN_ORCHESTRATOR_STEP):
            self.logger.log(
                "orchestrator_step",
                f"Routing job: {job_type}",
                {"job_type": job_type, "engagement_id": self.engagement_id}
            )
            
            if job_type == "recon":
                return self.run_recon(job)
            elif job_type == "scan":
                return self.run_scan(job)
            elif job_type == "analyze":
                return self.run_analysis(job)
            elif job_type == "report":
                return self.run_reporting(job)
            elif job_type == "repo_scan":
                return self.run_repo_scan(job)
            else:
                raise ValueError(f"Unknown job type: {job_type}")
    
    def run_recon(self, job: Dict) -> Dict:
        """
        Execute reconnaissance phase
        
        Args:
            job: Job dictionary
        
        Returns:
            Recon results
        """
        self._check_timeout()
        
        target = job.get("target")
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="recon",
            target=target
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="recon",
            engagement_id=self.engagement_id,
            target=target
        )
        
        # Execute reconnaissance tools
        findings = self._execute_recon_tools(target, job.get("budget", {}))
        
        # Save findings to database
        findings_count = len(findings)
        if self.finding_repo and findings:
            try:
                for finding in findings:
                    self.finding_repo.create_finding(
                        engagement_id=self.engagement_id,
                        finding_type=finding.get("type", "UNKNOWN"),
                        severity=finding.get("severity", "INFO"),
                        endpoint=finding.get("endpoint", ""),
                        evidence=finding.get("evidence", {}),
                        confidence=finding.get("confidence", 0.5),
                        source_tool=finding.get("tool", "unknown"),
                    )
            except Exception as e:
                logger.error(f"Failed to save findings: {e}")
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="created",
            to_state="awaiting_approval",
            reason="Reconnaissance completed"
        )
        
        return {
            "phase": "recon",
            "status": "completed",
            "findings_count": findings_count,
            "next_state": "awaiting_approval",
            "trace_id": get_trace_id(),
        }
    
    def _execute_recon_tools(self, target: str, budget: Dict) -> List[Dict]:
        """
        Execute reconnaissance tools against target.
        
        Args:
            target: Target URL
            budget: Budget configuration
            
        Returns:
            List of findings
        """
        all_findings = []
        
        # Execute httpx for endpoint discovery
        try:
            httpx_result = self.tool_runner.run(
                "httpx",
                ["-u", target, "-json", "-silent"],
                timeout=60
            )
            if httpx_result.get("success"):
                parsed = self.parser.parse("httpx", httpx_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "httpx")
                    if normalized:
                        all_findings.append(normalized)
        except Exception as e:
            logger.warning(f"httpx failed: {e}")
        
        # Execute katana for web crawling
        try:
            katana_result = self.tool_runner.run(
                "katana",
                ["-u", target, "-jsonl", "-silent", "-d", "3"],
                timeout=120
            )
            if katana_result.get("success"):
                parsed = self.parser.parse("katana", katana_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "katana")
                    if normalized:
                        all_findings.append(normalized)
        except Exception as e:
            logger.warning(f"katana failed: {e}")
        
        # Execute ffuf for fuzzing/directory discovery
        try:
            ffuf_result = self.tool_runner.run(
                "ffuf",
                ["-u", f"{target}/FUZZ", "-json"],
                timeout=180
            )
            if ffuf_result.get("success"):
                parsed = self.parser.parse("ffuf", ffuf_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "ffuf")
                    if normalized:
                        all_findings.append(normalized)
        except Exception as e:
            logger.warning(f"ffuf failed: {e}")
        
        # Execute amass for subdomain enumeration
        try:
            amass_result = self.tool_runner.run(
                "amass",
                ["enum", "-d", target.replace("https://", "").replace("http://", "").split("/")[0], "-json"],
                timeout=300
            )
            if amass_result.get("success"):
                parsed = self.parser.parse("amass", amass_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "amass")
                    if normalized:
                        all_findings.append(normalized)
        except Exception as e:
            logger.warning(f"amass failed: {e}")
        
        # Execute naabu for port scanning
        try:
            target_domain = target.replace("https://", "").replace("http://", "").split("/")[0]
            naabu_result = self.tool_runner.run(
                "naabu",
                ["-host", target_domain, "-json"],
                timeout=120
            )
            if naabu_result.get("success"):
                parsed = self.parser.parse("naabu", naabu_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "naabu")
                    if normalized:
                        all_findings.append(normalized)
        except Exception as e:
            logger.warning(f"naabu failed: {e}")
        
        # Execute whatweb for technology fingerprinting
        try:
            whatweb_result = self.tool_runner.run(
                "whatweb",
                ["--format=json", target],
                timeout=120
            )
            if whatweb_result.get("success"):
                parsed = self.parser.parse("whatweb", whatweb_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "whatweb")
                    if normalized:
                        all_findings.append(normalized)
        except Exception as e:
            logger.warning(f"whatweb failed: {e}")
        
        # Execute nikto for web server scanning
        try:
            nikto_result = self.tool_runner.run(
                "nikto",
                ["-h", target, "-Format", "csv"],
                timeout=300
            )
            if nikto_result.get("success"):
                parsed = self.parser.parse("nikto", nikto_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "nikto")
                    if normalized:
                        all_findings.append(normalized)
        except Exception as e:
            logger.warning(f"nikto failed: {e}")
        
        # Execute gau for known URLs
        try:
            gau_result = self.tool_runner.run(
                "gau",
                [target, "--json"],
                timeout=180
            )
            if gau_result.get("success"):
                parsed = self.parser.parse("gau", gau_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "gau")
                    if normalized:
                        all_findings.append(normalized)
        except Exception as e:
            logger.warning(f"gau failed: {e}")
        
        # Execute waybackurls for historical URLs
        try:
            wayback_result = self.tool_runner.run(
                "waybackurls",
                [target],
                timeout=120
            )
            if wayback_result.get("success"):
                parsed = self.parser.parse("waybackurls", wayback_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "waybackurls")
                    if normalized:
                        all_findings.append(normalized)
        except Exception as e:
            logger.warning(f"waybackurls failed: {e}")
        
        return all_findings
    
    def _normalize_finding(self, raw_finding: Dict, tool: str) -> Optional[Dict]:
        """
        Normalize a raw finding to VulnerabilityFinding schema.
        
        Args:
            raw_finding: Raw finding from parser
            tool: Tool name
            
        Returns:
            Normalized finding, or None if invalid
        """
        try:
            finding = self.normalizer.normalize(raw_finding, tool)
            return {
                "type": finding.type,
                "severity": finding.severity.value if hasattr(finding.severity, 'value') else finding.severity,
                "endpoint": finding.endpoint,
                "evidence": finding.evidence,
                "confidence": finding.confidence,
                "source_tool": tool,
            }
        except Exception as e:
            logger.warning(f"Failed to normalize finding: {e}")
            return None
    
    def run_scan(self, job: Dict) -> Dict:
        """
        Execute scanning phase
        
        Args:
            job: Job dictionary
        
        Returns:
            Scan results
        """
        self._check_timeout()
        
        targets = job.get("targets", [])
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="scan",
            target=str(targets)
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="scan",
            engagement_id=self.engagement_id,
            target=str(targets)
        )
        
        # Execute scanning tools against targets
        findings = self._execute_scan_tools(targets, job.get("budget", {}))
        
        # Save findings to database
        findings_count = len(findings)
        if self.finding_repo and findings:
            try:
                for finding in findings:
                    self.finding_repo.create_finding(
                        engagement_id=self.engagement_id,
                        finding_type=finding.get("type", "UNKNOWN"),
                        severity=finding.get("severity", "INFO"),
                        endpoint=finding.get("endpoint", ""),
                        evidence=finding.get("evidence", {}),
                        confidence=finding.get("confidence", 0.5),
                        source_tool=finding.get("source_tool", "unknown"),
                    )
            except Exception as e:
                logger.error(f"Failed to save findings: {e}")
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="awaiting_approval",
            to_state="analyzing",
            reason="Scanning completed"
        )
        
        return {
            "phase": "scan",
            "status": "completed",
            "findings_count": findings_count,
            "next_state": "analyzing",
            "trace_id": get_trace_id(),
        }
    
    def _execute_scan_tools(self, targets: List[str], budget: Dict) -> List[Dict]:
        """
        Execute scanning tools against targets.
        
        Args:
            targets: List of target URLs
            budget: Budget configuration
            
        Returns:
            List of findings
        """
        all_findings = []
        
        for target in targets:
            # Execute Nuclei for vulnerability scanning
            try:
                nuclei_result = self.tool_runner.run(
                    "nuclei",
                    ["-u", target, "-json", "-silent"],
                    timeout=300
                )
                if nuclei_result.get("success"):
                    parsed = self.parser.parse("nuclei", nuclei_result.get("stdout", ""))
                    for p in parsed:
                        normalized = self._normalize_finding(p, "nuclei")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"nuclei failed for {target}: {e}")
            
            # Execute dalfox for XSS
            try:
                dalfox_result = self.tool_runner.run(
                    "dalfox",
                    ["url", target, "-json"],
                    timeout=300
                )
                if dalfox_result.get("success"):
                    parsed = self.parser.parse("dalfox", dalfox_result.get("stdout", ""))
                    for p in parsed:
                        normalized = self._normalize_finding(p, "dalfox")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"dalfox failed for {target}: {e}")
            
            # Execute sqlmap for SQL injection
            try:
                sqlmap_result = self.tool_runner.run(
                    "sqlmap",
                    ["-u", target, "--batch", "--json-output", "/tmp/sqlmap.json"],
                    timeout=300
                )
                if sqlmap_result.get("success"):
                    # Read JSON output if available
                    import json
                    try:
                        with open("/tmp/sqlmap.json", "r") as f:
                            sqlmap_output = f.read()
                        parsed = self.parser.parse("sqlmap", sqlmap_output)
                    except:
                        parsed = []
                    
                    for p in parsed:
                        normalized = self._normalize_finding(p, "sqlmap")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"sqlmap failed for {target}: {e}")
            
            # Execute arjun for parameter discovery
            try:
                arjun_result = self.tool_runner.run(
                    "arjun",
                    ["-u", target, "-m", "GET", "-o", "/tmp/arjun.json", "-t", "20"],
                    timeout=180
                )
                if arjun_result.get("success"):
                    try:
                        with open("/tmp/arjun.json", "r") as f:
                            arjun_output = f.read()
                        parsed = self.parser.parse("arjun", arjun_output)
                    except:
                        parsed = []
                    
                    for p in parsed:
                        normalized = self._normalize_finding(p, "arjun")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"arjun failed for {target}: {e}")
            
            # Execute jwt_tool for JWT vulnerability testing
            try:
                # First check if target has JWT tokens
                jwt_result = self.tool_runner.run(
                    "jwt_tool",
                    ["-u", target, "-C", "-d"],
                    timeout=120
                )
                if jwt_result.get("success"):
                    parsed = self.parser.parse("jwt_tool", jwt_result.get("stdout", ""))
                    for p in parsed:
                        normalized = self._normalize_finding(p, "jwt_tool")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"jwt_tool failed for {target}: {e}")
            
            # Execute commix for command injection testing
            try:
                commix_result = self.tool_runner.run(
                    "commix",
                    ["--url", target, "--batch", "--json-output", "/tmp/commix.json"],
                    timeout=300
                )
                if commix_result.get("success"):
                    try:
                        with open("/tmp/commix.json", "r") as f:
                            commix_output = f.read()
                        parsed = self.parser.parse("commix", commix_output)
                    except:
                        parsed = []
                    
                    for p in parsed:
                        normalized = self._normalize_finding(p, "commix")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"commix failed for {target}: {e}")
            
            # Execute testssl for TLS vulnerability scanning
            try:
                testssl_result = self.tool_runner.run(
                    "testssl",
                    ["--jsonfile", "/tmp/testssl.json", target],
                    timeout=300
                )
                if testssl_result.get("success"):
                    try:
                        with open("/tmp/testssl.json", "r") as f:
                            testssl_output = f.read()
                        parsed = self.parser.parse("testssl", testssl_output)
                    except:
                        parsed = []
                    
                    for p in parsed:
                        normalized = self._normalize_finding(p, "testssl")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"testssl failed for {target}: {e}")
            
            # Execute comprehensive web scanner
            try:
                web_scanner = WebScanner(timeout=10, rate_limit=0.1)
                web_findings = web_scanner.scan(target)
                
                for wf in web_findings:
                    # Map web scanner findings to normalized format
                    normalized = self._normalize_finding(wf, "web_scanner")
                    if normalized:
                        all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"WebScanner failed for {target}: {e}")
        
        return all_findings
    
    def run_analysis(self, job: Dict) -> Dict:
        """
        Execute analysis phase
        
        Args:
            job: Job dictionary
        
        Returns:
            Analysis results
        """
        self._check_timeout()
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="analyze"
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="analyze",
            engagement_id=self.engagement_id
        )
        
        # Get findings from database
        findings = []
        if self.finding_repo:
            try:
                findings = self.finding_repo.get_findings_by_engagement(self.engagement_id)
                findings = [f.to_dict() for f in findings]
            except Exception as e:
                logger.warning(f"Failed to load findings: {e}")
        
        # Import Intelligence Engine and Loop Budget
        from intelligence_engine import IntelligenceEngine
        from loop_budget_manager import LoopBudgetManager
        from snapshot_manager import SnapshotManager
        
        # Create snapshot
        db_conn = os.getenv("DATABASE_URL")
        snapshot_mgr = SnapshotManager(db_conn)
        snapshot = snapshot_mgr.create_snapshot(self.engagement_id)
        
        # Initialize budget manager
        budget_config = job.get("budget", {})
        budget_mgr = LoopBudgetManager(self.engagement_id, budget_config)
        
        # Evaluate with Intelligence Engine
        engine = IntelligenceEngine(db_conn)
        snapshot["findings"] = findings
        snapshot["loop_budget"] = budget_mgr.to_dict()
        
        evaluation = engine.evaluate(snapshot)
        
        # Extract actions
        actions = evaluation.get("actions", [])
        
        # Check budget for continuation
        next_state = "reporting"
        for action in actions:
            can_continue, reason = budget_mgr.can_continue(action)
            if can_continue:
                budget_mgr.consume(action)
                next_state = "recon"  # Loop back for more scanning
            else:
                logger.info(f"Budget exhausted: {reason}")
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="analyzing",
            to_state=next_state,
            reason="Analysis completed" if next_state == "reporting" else "Additional targets discovered"
        )
        
        return {
            "phase": "analyze",
            "status": "completed",
            "actions": actions,
            "scored_findings": evaluation.get("scored_findings", []),
            "reasoning": evaluation.get("reasoning", ""),
            "next_state": next_state,
            "trace_id": get_trace_id(),
        }
    
    def run_reporting(self, job: Dict) -> Dict:
        """
        Execute reporting phase
        
        Args:
            job: Job dictionary
            
        Returns:
            Reporting results
        """
        self._check_timeout()
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="report"
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="report",
            engagement_id=self.engagement_id
        )
        
        # Generate final report
        # Transition to complete state
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="reporting",
            to_state="complete",
            reason="Reporting completed"
        )
        
        return {
            "phase": "report",
            "status": "completed",
            "next_state": "complete",
            "trace_id": get_trace_id(),
        }
    
    def _check_timeout(self):
        """
        Check if hard timeout has been exceeded
        
        Raises:
            EngagementTimeoutError: If timeout exceeded
        """
        if self.start_time is None:
            return
        
        elapsed = time.time() - self.start_time
        
        if elapsed > self.HARD_TIMEOUT_SECONDS:
            # Log timeout event
            self._log_timeout_event(elapsed)
            
            raise EngagementTimeoutError(
                f"Engagement {self.engagement_id} exceeded hard timeout "
                f"of {self.HARD_TIMEOUT_SECONDS} seconds (elapsed: {elapsed:.2f}s)"
            )
    
    def _log_timeout_event(self, elapsed_seconds: float):
        """
        Log timeout event to execution logs
        
        Args:
            elapsed_seconds: Elapsed time in seconds
        """
        # Log timeout event
        logger.warning(
            f"Engagement {self.engagement_id} exceeded hard timeout. "
            f"Elapsed: {elapsed_seconds:.2f}s, Limit: {self.HARD_TIMEOUT_SECONDS}s"
        )
    
    def get_elapsed_time(self) -> float:
        """
        Get elapsed time since start
        
        Returns:
            Elapsed time in seconds
        """
        if self.start_time is None:
            return 0.0
        
        return time.time() - self.start_time
    
    def get_remaining_time(self) -> float:
        """
        Get remaining time before timeout
        
        Returns:
            Remaining time in seconds
        """
        elapsed = self.get_elapsed_time()
        return max(0.0, self.HARD_TIMEOUT_SECONDS - elapsed)
    
    def run_repo_scan(self, job: Dict) -> Dict:
        """
        Execute repository scanning phase (Semgrep static analysis)
        
        Args:
            job: Job dictionary with repo_url
            
        Returns:
            Repo scan results
        """
        self._check_timeout()
        
        repo_url = job.get("repo_url")
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="repo_scan",
            target=repo_url
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="repo_scan",
            engagement_id=self.engagement_id,
            target=repo_url
        )
        
        # Execute repository scan
        findings = self._execute_repo_scan(repo_url, job.get("budget", {}))
        
        # Save findings to database
        findings_count = len(findings)
        if self.finding_repo and findings:
            try:
                for finding in findings:
                    self.finding_repo.create_finding(
                        engagement_id=self.engagement_id,
                        finding_type=finding.get("type", "UNKNOWN"),
                        severity=finding.get("severity", "INFO"),
                        endpoint=finding.get("endpoint", ""),
                        evidence=finding.get("evidence", {}),
                        confidence=finding.get("confidence", 0.5),
                        source_tool=finding.get("tool", "semgrep"),
                    )
            except Exception as e:
                logger.error(f"Failed to save repo findings: {e}")
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="created",
            to_state="awaiting_approval",
            reason="Repository scan completed"
        )
        
        return {
            "phase": "repo_scan",
            "status": "completed",
            "findings_count": findings_count,
            "next_state": "awaiting_approval",
            "trace_id": get_trace_id(),
        }
    
    def _execute_repo_scan(self, repo_url: str, budget: Dict) -> List[Dict]:
        """
        Execute Semgrep scan on a repository using vibe-security-ultra custom rules.
        
        Args:
            repo_url: GitHub/GitLab repo URL
            budget: Budget configuration
            
        Returns:
            List of code vulnerability findings
        """
        import tempfile
        import shutil
        import subprocess
        import os
        
        all_findings = []
        
        # Get path to custom semgrep rules
        rules_dir = os.path.join(os.path.dirname(__file__), "semgrep_rules")
        
        temp_dir = tempfile.mkdtemp(prefix="argus_repo_scan_")
        
        try:
            # Clone repository
            clone_result = subprocess.run(
                ["git", "clone", "--depth", "1", repo_url, temp_dir],
                capture_output=True,
                text=True,
                timeout=120
            )
            
            if clone_result.returncode != 0:
                logger.warning(f"Failed to clone repo {repo_url}: {clone_result.stderr}")
                return []
            
            # First run with custom rules (vibe-security-ultra)
            custom_rules_path = os.path.join(rules_dir, "secrets")
            auto_rules_path = os.path.join(rules_dir, "auth")
            injection_rules_path = os.path.join(rules_dir, "injection")
            xss_rules_path = os.path.join(rules_dir, "xss")
            ssrf_rules_path = os.path.join(rules_dir, "ssrf")
            csrf_rules_path = os.path.join(rules_dir, "csrf")
            auto_rules_path2 = os.path.join(rules_dir, "auto")
            auth_rules_path = os.path.join(rules_dir, "auth")
            
            # Run semgrep with custom rules
            custom_configs = []
            for config_dir in [custom_rules_path, auto_rules_path, injection_rules_path, 
                           xss_rules_path, ssrf_rules_path, csrf_rules_path, auto_rules_path2, auth_rules_path]:
                if os.path.isdir(config_dir):
                    custom_configs.append(config_dir)
            
            # Run with auto rules as baseline
            semgrep_result = self.tool_runner.run(
                "semgrep",
                ["--json", "--config", "auto", temp_dir],
                timeout=300
            )
            
            if semgrep_result.get("success"):
                parsed = self.parser.parse(
                    "semgrep", 
                    semgrep_result.get("stdout", "")
                )
                for p in parsed:
                    normalized = self._normalize_finding(p, "semgrep")
                    if normalized:
                        all_findings.append(normalized)
            else:
                logger.warning(f"Semgrep auto scan failed: {semgrep_result.get('stderr')}")
            
            # Also try custom rules if available
            if custom_configs:
                for config in custom_configs[:3]:  # Limit to 3 rule sets to avoid timeout
                    try:
                        semgrep_result = self.tool_runner.run(
                            "semgrep",
                            ["--json", "--config", config, temp_dir],
                            timeout=180
                        )
                        if semgrep_result.get("success"):
                            parsed = self.parser.parse(
                                "semgrep", 
                                semgrep_result.get("stdout", "")
                            )
                            for p in parsed:
                                normalized = self._normalize_finding(p, "semgrep")
                                if normalized:
                                    # Avoid duplicates
                                    if not any(n.get("endpoint") == normalized.get("endpoint") for n in all_findings):
                                        all_findings.append(normalized)
                    except Exception as e:
                        logger.warning(f"Semgrep custom rules scan failed for {config}: {e}")
                
        except Exception as e:
            logger.warning(f"Repo scan failed: {e}")
        finally:
            # Cleanup temp directory
            try:
                shutil.rmtree(temp_dir)
            except:
                pass
        
        return all_findings
