"""
Orchestrator - Workflow executor ONLY (no decision-making)
Executes actions generated by Intelligence Engine

Requirements: 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 21.1, 21.2, 31.2, 31.3
"""
import time
from typing import Dict, List, Optional
from datetime import datetime
import os

from tracing import (
    TracingManager,
    TraceContext,
    get_trace_id,
    StructuredLogger,
    ExecutionSpan,
)
from websocket_events import (
    WebSocketEventPublisher,
    get_websocket_publisher,
)


class EngagementTimeoutError(Exception):
    """Raised when engagement exceeds hard timeout"""
    pass


class Orchestrator:
    """
    Workflow execution engine.
    Executes actions generated by Intelligence Engine without making decisions.
    """
    
    # Hard timeout: 3600 seconds (1 hour)
    HARD_TIMEOUT_SECONDS = 3600
    
    def __init__(self, engagement_id: str, trace_id: str = None):
        """
        Initialize Orchestrator
        
        Args:
            engagement_id: Engagement ID
            trace_id: Optional trace_id for distributed tracing
        """
        self.engagement_id = engagement_id
        self.start_time = None
        self.trace_id = trace_id
        
        # Initialize tracing components
        db_conn = os.getenv("DATABASE_URL")
        self.tracing_manager = TracingManager(db_conn)
        self.logger = StructuredLogger(db_conn)
        self.span_recorder = ExecutionSpan(db_conn)
        
        # Initialize WebSocket event publisher
        self.ws_publisher = get_websocket_publisher()
    
    def run(self, job: Dict) -> Dict:
        """
        Execute job workflow
        
        Args:
            job: Job dictionary with type and parameters
            
        Returns:
            Execution result
            
        Raises:
            EngagementTimeoutError: If hard timeout exceeded
        """
        # Start timer
        if self.start_time is None:
            self.start_time = time.time()
        
        # Check hard timeout
        self._check_timeout()
        
        # Route to appropriate workflow
        job_type = job.get("type")
        
        # Log orchestrator step with trace_id
        with self.span_recorder.span(ExecutionSpan.SPAN_ORCHESTRATOR_STEP):
            self.logger.log(
                "orchestrator_step",
                f"Routing job: {job_type}",
                {"job_type": job_type, "engagement_id": self.engagement_id}
            )
            
            if job_type == "recon":
                return self.run_recon(job)
            elif job_type == "scan":
                return self.run_scan(job)
            elif job_type == "analyze":
                return self.run_analysis(job)
            elif job_type == "report":
                return self.run_reporting(job)
            else:
                raise ValueError(f"Unknown job type: {job_type}")
    
    def run_recon(self, job: Dict) -> Dict:
        """
        Execute reconnaissance phase
        
        Args:
            job: Job dictionary
            
        Returns:
            Recon results
        """
        self._check_timeout()
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="recon",
            target=job.get("target")
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="recon",
            engagement_id=self.engagement_id,
            target=job.get("target")
        )
        
        # Execute reconnaissance tools (httpx, nuclei)
        # This is a placeholder - actual implementation would call ToolExecutor
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="created",
            to_state="awaiting_approval",
            reason="Reconnaissance completed"
        )
        
        return {
            "phase": "recon",
            "status": "completed",
            "findings_count": 0,
            "next_state": "awaiting_approval",
            "trace_id": get_trace_id(),
        }
    
    def run_scan(self, job: Dict) -> Dict:
        """
        Execute scanning phase
        
        Args:
            job: Job dictionary
            
        Returns:
            Scan results
        """
        self._check_timeout()
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="scan",
            target=str(job.get("targets", []))
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="scan",
            engagement_id=self.engagement_id,
            target=str(job.get("targets", []))
        )
        
        # Execute scanning tools based on Intelligence Engine actions
        # This is a placeholder - actual implementation would call ToolExecutor
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="awaiting_approval",
            to_state="analyzing",
            reason="Scanning completed"
        )
        
        return {
            "phase": "scan",
            "status": "completed",
            "findings_count": 0,
            "next_state": "analyzing",
            "trace_id": get_trace_id(),
        }
    
    def run_analysis(self, job: Dict) -> Dict:
        """
        Execute analysis phase
        
        Args:
            job: Job dictionary
            
        Returns:
            Analysis results
        """
        self._check_timeout()
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="analyze"
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="analyze",
            engagement_id=self.engagement_id
        )
        
        # Create decision snapshot
        # Call Intelligence Engine evaluate()
        # Check Loop Budget can_continue()
        # Generate next actions or transition to reporting
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="analyzing",
            to_state="reporting",
            reason="Analysis completed"
        )
        
        return {
            "phase": "analyze",
            "status": "completed",
            "actions": [],
            "next_state": "reporting",
            "trace_id": get_trace_id(),
        }
    
    def run_reporting(self, job: Dict) -> Dict:
        """
        Execute reporting phase
        
        Args:
            job: Job dictionary
            
        Returns:
            Reporting results
        """
        self._check_timeout()
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="report"
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="report",
            engagement_id=self.engagement_id
        )
        
        # Generate final report
        # Transition to complete state
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="reporting",
            to_state="complete",
            reason="Reporting completed"
        )
        
        return {
            "phase": "report",
            "status": "completed",
            "next_state": "complete",
            "trace_id": get_trace_id(),
        }
    
    def _check_timeout(self):
        """
        Check if hard timeout has been exceeded
        
        Raises:
            EngagementTimeoutError: If timeout exceeded
        """
        if self.start_time is None:
            return
        
        elapsed = time.time() - self.start_time
        
        if elapsed > self.HARD_TIMEOUT_SECONDS:
            # Log timeout event
            self._log_timeout_event(elapsed)
            
            raise EngagementTimeoutError(
                f"Engagement {self.engagement_id} exceeded hard timeout "
                f"of {self.HARD_TIMEOUT_SECONDS} seconds (elapsed: {elapsed:.2f}s)"
            )
    
    def _log_timeout_event(self, elapsed_seconds: float):
        """
        Log timeout event to execution logs
        
        Args:
            elapsed_seconds: Elapsed time in seconds
        """
        # In production, this would write to execution_logs table
        print(f"TIMEOUT: Engagement {self.engagement_id} exceeded hard timeout")
        print(f"  Elapsed: {elapsed_seconds:.2f} seconds")
        print(f"  Limit: {self.HARD_TIMEOUT_SECONDS} seconds")
    
    def get_elapsed_time(self) -> float:
        """
        Get elapsed time since start
        
        Returns:
            Elapsed time in seconds
        """
        if self.start_time is None:
            return 0.0
        
        return time.time() - self.start_time
    
    def get_remaining_time(self) -> float:
        """
        Get remaining time before timeout
        
        Returns:
            Remaining time in seconds
        """
        elapsed = self.get_elapsed_time()
        return max(0.0, self.HARD_TIMEOUT_SECONDS - elapsed)
