"""
Orchestrator - Workflow executor ONLY (no decision-making)
Executes actions generated by Intelligence Engine

Requirements: 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 21.1, 21.2, 31.2, 31.3
"""
import logging
import time
from typing import Dict, List, Optional
import os

logger = logging.getLogger(__name__)

from tracing import (
    TracingManager,
    TraceContext,
    get_trace_id,
    StructuredLogger,
    ExecutionSpan,
)
from websocket_events import (
    WebSocketEventPublisher,
    get_websocket_publisher,
)
from tools.tool_runner import ToolRunner
from tools.web_scanner import WebScanner
from parsers.parser import Parser
from parsers.normalizer import FindingNormalizer
from database.repositories.finding_repository import FindingRepository
from database.repositories.engagement_repository import EngagementRepository


class EngagementTimeoutError(Exception):
    """Raised when engagement exceeds hard timeout"""
    pass


class Orchestrator:
    """
    Workflow execution engine.
    Executes actions generated by Intelligence Engine without making decisions.
    """
    
    # Hard timeout: 3600 seconds (1 hour)
    HARD_TIMEOUT_SECONDS = 3600
    
    def __init__(self, engagement_id: str, trace_id: str = None):
        """
        Initialize Orchestrator
        
        Args:
            engagement_id: Engagement ID
            trace_id: Optional trace_id for distributed tracing
        """
        self.engagement_id = engagement_id
        self.start_time = None
        self.trace_id = trace_id
        
        # Initialize tracing components
        db_conn = os.getenv("DATABASE_URL")
        self.tracing_manager = TracingManager(db_conn)
        self.logger = StructuredLogger(db_conn)
        self.span_recorder = ExecutionSpan(db_conn)
        
        # Initialize WebSocket event publisher
        self.ws_publisher = get_websocket_publisher()
        
        # Initialize execution components
        self.tool_runner = ToolRunner(connection_string=db_conn)
        self.parser = Parser(connection_string=db_conn)
        self.normalizer = FindingNormalizer()
        self.finding_repo = FindingRepository(db_conn) if db_conn else None
        self.engagement_repo = EngagementRepository(db_conn) if db_conn else None
    
    def run(self, job: Dict) -> Dict:
        """
        Execute job workflow
        
        Args:
            job: Job dictionary with type and parameters
            
        Returns:
            Execution result
            
        Raises:
            EngagementTimeoutError: If hard timeout exceeded
        """
        # Start timer
        if self.start_time is None:
            self.start_time = time.time()
        
        # Check hard timeout
        self._check_timeout()
        
        # Route to appropriate workflow
        job_type = job.get("type")
        
        # Log orchestrator step with trace_id
        with self.span_recorder.span(ExecutionSpan.SPAN_ORCHESTRATOR_STEP):
            self.logger.log(
                "orchestrator_step",
                f"Routing job: {job_type}",
                {"job_type": job_type, "engagement_id": self.engagement_id}
            )
            
            if job_type == "recon":
                return self.run_recon(job)
            elif job_type == "scan":
                return self.run_scan(job)
            elif job_type == "analyze":
                return self.run_analysis(job)
            elif job_type == "report":
                return self.run_reporting(job)
            elif job_type == "repo_scan":
                return self.run_repo_scan(job)
            else:
                raise ValueError(f"Unknown job type: {job_type}")
    
    def run_recon(self, job: Dict) -> Dict:
        """
        Execute reconnaissance phase
        
        Args:
            job: Job dictionary
        
        Returns:
            Recon results
        """
        self._check_timeout()
        
        target = job.get("target")
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="recon",
            target=target
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="recon",
            engagement_id=self.engagement_id,
            target=target
        )
        
        # Execute reconnaissance tools
        aggressiveness = job.get("aggressiveness", "default")
        findings = self._execute_recon_tools(target, job.get("budget", {}), aggressiveness)
        
        # Save findings to database
        findings_count = len(findings)
        if self.finding_repo and findings:
            try:
                for finding in findings:
                    self.finding_repo.create_finding(
                        engagement_id=self.engagement_id,
                        finding_type=finding.get("type", "UNKNOWN"),
                        severity=finding.get("severity", "INFO"),
                        endpoint=finding.get("endpoint", ""),
                        evidence=finding.get("evidence", {}),
                        confidence=finding.get("confidence", 0.5),
                        source_tool=finding.get("tool", "unknown"),
                    )
            except Exception as e:
                logger.error(f"Failed to save findings: {e}")
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="created",
            to_state="awaiting_approval",
            reason="Reconnaissance completed"
        )
        
        return {
            "phase": "recon",
            "status": "completed",
            "findings_count": findings_count,
            "next_state": "awaiting_approval",
            "trace_id": get_trace_id(),
        }
    
    def _execute_recon_tools(self, target: str, budget: Dict, aggressiveness: str = "default") -> List[Dict]:
        """
        Execute reconnaissance tools against target.
        
        Args:
            target: Target URL
            budget: Budget configuration
            aggressiveness: Scan aggressiveness level (default, high, extreme)
            
        Returns:
            List of findings
        """
        all_findings = []
        target_domain = target.replace("https://", "").replace("http://", "").split("/")[0]

        # Aggressiveness config
        agg = aggressiveness or "default"
        katana_depth = {"default": "3", "high": "5", "extreme": "7"}.get(agg, "3")
        naabu_ports = {"default": "-top-ports", "high": "-top-ports", "extreme": "-p-"}.get(agg, "-top-ports")
        naabu_port_val = {"default": "1000", "high": "10000", "extreme": "1-65535"}.get(agg, "1000")
        amass_mode = {"default": ["enum", "-d"], "high": ["enum", "-d"], "extreme": ["enum", "-d", "-brute", "-w"]}.get(agg, ["enum", "-d"])

        def _emit(tool: str, activity: str, status: str, items: int = None, details: str = None):
            self.ws_publisher.publish_scanner_activity(
                engagement_id=self.engagement_id,
                tool_name=tool,
                activity=activity,
                status=status,
                target=target_domain,
                items_found=items,
                details=details,
            )
        
        # Execute httpx for endpoint discovery
        _emit("httpx", "Discovering live endpoints and probing HTTP services", "started")
        try:
            httpx_result = self.tool_runner.run(
                "httpx",
                ["-u", target, "-json", "-silent"],
                timeout=60
            )
            parsed_count = 0
            if httpx_result.get("success"):
                parsed = self.parser.parse("httpx", httpx_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "httpx")
                    if normalized:
                        all_findings.append(normalized)
                        parsed_count += 1
            _emit("httpx", "Live endpoint discovery complete", "completed", items=parsed_count)
        except Exception as e:
            _emit("httpx", f"Live endpoint discovery failed: {str(e)}", "failed")
            logger.warning(f"httpx failed: {e}")
        
        # Execute katana for web crawling
        _emit("katana", f"Crawling application routes and links up to depth {katana_depth}", "started")
        try:
            katana_result = self.tool_runner.run(
                "katana",
                ["-u", target, "-jsonl", "-silent", "-d", katana_depth],
                timeout=180 if agg == "extreme" else 120
            )
            parsed_count = 0
            if katana_result.get("success"):
                parsed = self.parser.parse("katana", katana_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "katana")
                    if normalized:
                        all_findings.append(normalized)
                        parsed_count += 1
            _emit("katana", "Web crawling complete — mapped application surface", "completed", items=parsed_count)
        except Exception as e:
            _emit("katana", f"Web crawling failed: {str(e)}", "failed")
            logger.warning(f"katana failed: {e}")
        
        # Execute ffuf for fuzzing/directory discovery
        wordlist_dir = "/Users/mac/Documents/Argus-/argus-workers/wordlists"
        ffuf_wordlist = {
            "default": os.path.join(wordlist_dir, "common.txt"),
            "high": os.path.join(wordlist_dir, "extended.txt"),
            "extreme": os.path.join(wordlist_dir, "comprehensive.txt"),
        }.get(agg, os.path.join(wordlist_dir, "common.txt"))
        ffuf_wordlist_name = os.path.basename(ffuf_wordlist)
        _emit("ffuf", f"Fuzzing directories with {ffuf_wordlist_name} wordlist", "started")
        try:
            ffuf_cmd = ["-u", f"{target}/FUZZ", "-w", ffuf_wordlist, "-json"]
            if agg == "high":
                ffuf_cmd.extend(["-t", "50"])
            elif agg == "extreme":
                ffuf_cmd.extend(["-t", "100", "-mc", "all"])
            ffuf_result = self.tool_runner.run(
                "ffuf",
                ffuf_cmd,
                timeout=300 if agg == "extreme" else 180
            )
            parsed_count = 0
            if ffuf_result.get("success"):
                parsed = self.parser.parse("ffuf", ffuf_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "ffuf")
                    if normalized:
                        all_findings.append(normalized)
                        parsed_count += 1
            _emit("ffuf", "Directory fuzzing complete", "completed", items=parsed_count)
        except Exception as e:
            _emit("ffuf", f"Directory fuzzing failed: {str(e)}", "failed")
            logger.warning(f"ffuf failed: {e}")
        
        # Execute amass for subdomain enumeration
        amass_desc = "passive" if agg == "default" else "active + passive" if agg == "high" else "brute force + all sources"
        _emit("amass", f"Enumerating subdomains for {target_domain} ({amass_desc})", "started")
        try:
            amass_cmd = amass_mode + [target_domain, "-json"]
            amass_timeout = 300 if agg == "default" else 600 if agg == "high" else 1200
            amass_result = self.tool_runner.run(
                "amass",
                amass_cmd,
                timeout=amass_timeout
            )
            parsed_count = 0
            if amass_result.get("success"):
                parsed = self.parser.parse("amass", amass_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "amass")
                    if normalized:
                        all_findings.append(normalized)
                        parsed_count += 1
            _emit("amass", f"Subdomain enumeration complete — found {parsed_count} subdomains", "completed", items=parsed_count)
        except Exception as e:
            _emit("amass", f"Subdomain enumeration failed: {str(e)}", "failed")
            logger.warning(f"amass failed: {e}")
        
        # Execute naabu for port scanning
        port_desc = "top 1000" if agg == "default" else "top 10,000" if agg == "high" else "full range 1-65535"
        _emit("naabu", f"Probing open ports on {target_domain} ({port_desc})", "started")
        try:
            naabu_cmd = ["-host", target_domain, "-json"]
            if naabu_ports == "-p-":
                naabu_cmd.append("-p-")
            else:
                naabu_cmd.extend(["-top-ports", naabu_port_val])
            naabu_timeout = 120 if agg == "default" else 300 if agg == "high" else 900
            naabu_result = self.tool_runner.run(
                "naabu",
                naabu_cmd,
                timeout=naabu_timeout
            )
            parsed_count = 0
            if naabu_result.get("success"):
                parsed = self.parser.parse("naabu", naabu_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "naabu")
                    if normalized:
                        all_findings.append(normalized)
                        parsed_count += 1
            _emit("naabu", f"Port scan complete — found {parsed_count} open ports", "completed", items=parsed_count)
        except Exception as e:
            _emit("naabu", f"Port scan failed: {str(e)}", "failed")
            logger.warning(f"naabu failed: {e}")
        
        # Execute whatweb for technology fingerprinting
        _emit("whatweb", "Fingerprinting web technologies and server stack", "started")
        try:
            whatweb_result = self.tool_runner.run(
                "whatweb",
                ["--format=json", target],
                timeout=120
            )
            parsed_count = 0
            if whatweb_result.get("success"):
                parsed = self.parser.parse("whatweb", whatweb_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "whatweb")
                    if normalized:
                        all_findings.append(normalized)
                        parsed_count += 1
            _emit("whatweb", "Technology fingerprinting complete", "completed", items=parsed_count)
        except Exception as e:
            _emit("whatweb", f"Technology fingerprinting failed: {str(e)}", "failed")
            logger.warning(f"whatweb failed: {e}")
        
        # Execute nikto for web server scanning
        _emit("nikto", "Scanning web server for misconfigurations and known issues", "started")
        try:
            nikto_result = self.tool_runner.run(
                "nikto",
                ["-h", target, "-Format", "csv"],
                timeout=300
            )
            parsed_count = 0
            if nikto_result.get("success"):
                parsed = self.parser.parse("nikto", nikto_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "nikto")
                    if normalized:
                        all_findings.append(normalized)
                        parsed_count += 1
            _emit("nikto", "Web server scan complete", "completed", items=parsed_count)
        except Exception as e:
            _emit("nikto", f"Web server scan failed: {str(e)}", "failed")
            logger.warning(f"nikto failed: {e}")
        
        # Execute gau for known URLs
        _emit("gau", "Fetching known URLs from passive archives (gau)", "started")
        try:
            gau_result = self.tool_runner.run(
                "gau",
                [target, "--json"],
                timeout=180
            )
            parsed_count = 0
            if gau_result.get("success"):
                parsed = self.parser.parse("gau", gau_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "gau")
                    if normalized:
                        all_findings.append(normalized)
                        parsed_count += 1
            _emit("gau", "Passive URL discovery complete", "completed", items=parsed_count)
        except Exception as e:
            _emit("gau", f"Passive URL discovery failed: {str(e)}", "failed")
            logger.warning(f"gau failed: {e}")
        
        # Execute waybackurls for historical URLs
        _emit("waybackurls", "Retrieving historical URLs from Wayback Machine", "started")
        try:
            wayback_result = self.tool_runner.run(
                "waybackurls",
                [target],
                timeout=120
            )
            parsed_count = 0
            if wayback_result.get("success"):
                parsed = self.parser.parse("waybackurls", wayback_result.get("stdout", ""))
                for p in parsed:
                    normalized = self._normalize_finding(p, "waybackurls")
                    if normalized:
                        all_findings.append(normalized)
                        parsed_count += 1
            _emit("waybackurls", "Historical URL retrieval complete", "completed", items=parsed_count)
        except Exception as e:
            _emit("waybackurls", f"Historical URL retrieval failed: {str(e)}", "failed")
            logger.warning(f"waybackurls failed: {e}")
        
        return all_findings
    
    def _normalize_finding(self, raw_finding: Dict, tool: str) -> Optional[Dict]:
        """
        Normalize a raw finding to VulnerabilityFinding schema.
        
        Args:
            raw_finding: Raw finding from parser
            tool: Tool name
            
        Returns:
            Normalized finding, or None if invalid
        """
        try:
            finding = self.normalizer.normalize(raw_finding, tool)
            return {
                "type": finding.type,
                "severity": finding.severity.value if hasattr(finding.severity, 'value') else finding.severity,
                "endpoint": finding.endpoint,
                "evidence": finding.evidence,
                "confidence": finding.confidence,
                "source_tool": tool,
            }
        except Exception as e:
            logger.warning(f"Failed to normalize finding: {e}")
            return None
    
    def run_scan(self, job: Dict) -> Dict:
        """
        Execute scanning phase
        
        Args:
            job: Job dictionary
        
        Returns:
            Scan results
        """
        self._check_timeout()
        
        targets = job.get("targets", [])
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="scan",
            target=str(targets)
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="scan",
            engagement_id=self.engagement_id,
            target=str(targets)
        )
        
        # Execute scanning tools against targets
        scan_aggressiveness = job.get("aggressiveness", "default")
        findings = self._execute_scan_tools(targets, job.get("budget", {}), scan_aggressiveness)
        
        # Save findings to database
        findings_count = len(findings)
        if self.finding_repo and findings:
            try:
                for finding in findings:
                    self.finding_repo.create_finding(
                        engagement_id=self.engagement_id,
                        finding_type=finding.get("type", "UNKNOWN"),
                        severity=finding.get("severity", "INFO"),
                        endpoint=finding.get("endpoint", ""),
                        evidence=finding.get("evidence", {}),
                        confidence=finding.get("confidence", 0.5),
                        source_tool=finding.get("source_tool", "unknown"),
                    )
            except Exception as e:
                logger.error(f"Failed to save findings: {e}")
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="awaiting_approval",
            to_state="analyzing",
            reason="Scanning completed"
        )
        
        return {
            "phase": "scan",
            "status": "completed",
            "findings_count": findings_count,
            "next_state": "analyzing",
            "trace_id": get_trace_id(),
        }
    
    def _execute_scan_tools(self, targets: List[str], budget: Dict, aggressiveness: str = "default") -> List[Dict]:
        """
        Execute scanning tools against targets.
        
        Args:
            targets: List of target URLs
            budget: Budget configuration
            aggressiveness: Scan aggressiveness level (default, high, extreme)
            
        Returns:
            List of findings
        """
        all_findings = []
        agg = aggressiveness or "default"
        
        for target in targets:
            # Execute Nuclei for vulnerability scanning
            try:
                nuclei_cmd = ["-u", target, "-json", "-silent"]
                nuclei_timeout = 300
                if agg == "high":
                    nuclei_cmd.extend(["-severity", "low,medium,high,critical"])
                    nuclei_timeout = 600
                elif agg == "extreme":
                    nuclei_cmd.extend(["-severity", "info,low,medium,high,critical", "-tags", "fuzz"])
                    nuclei_timeout = 1200
                nuclei_result = self.tool_runner.run(
                    "nuclei",
                    nuclei_cmd,
                    timeout=nuclei_timeout
                )
                if nuclei_result.get("success"):
                    parsed = self.parser.parse("nuclei", nuclei_result.get("stdout", ""))
                    for p in parsed:
                        normalized = self._normalize_finding(p, "nuclei")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"nuclei failed for {target}: {e}")
            
            # Execute dalfox for XSS
            try:
                dalfox_cmd = ["url", target, "-json"]
                dalfox_timeout = 300
                if agg == "high":
                    dalfox_cmd.append("-b")
                    dalfox_timeout = 600
                elif agg == "extreme":
                    dalfox_cmd.extend(["-b", "--deep-dom"])
                    dalfox_timeout = 1200
                dalfox_result = self.tool_runner.run(
                    "dalfox",
                    dalfox_cmd,
                    timeout=dalfox_timeout
                )
                if dalfox_result.get("success"):
                    parsed = self.parser.parse("dalfox", dalfox_result.get("stdout", ""))
                    for p in parsed:
                        normalized = self._normalize_finding(p, "dalfox")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"dalfox failed for {target}: {e}")
            
            # Execute sqlmap for SQL injection
            try:
                sqlmap_cmd = ["-u", target, "--batch", "--json-output", "/tmp/sqlmap.json"]
                sqlmap_timeout = 300
                if agg == "high":
                    sqlmap_cmd.extend(["--level", "3", "--risk", "2"])
                    sqlmap_timeout = 600
                elif agg == "extreme":
                    sqlmap_cmd.extend(["--level", "5", "--risk", "3", "--all"])
                    sqlmap_timeout = 1800
                sqlmap_result = self.tool_runner.run(
                    "sqlmap",
                    sqlmap_cmd,
                    timeout=sqlmap_timeout
                )
                if sqlmap_result.get("success"):
                    # Read JSON output if available
                    import json
                    try:
                        with open("/tmp/sqlmap.json", "r") as f:
                            sqlmap_output = f.read()
                        parsed = self.parser.parse("sqlmap", sqlmap_output)
                    except:
                        parsed = []
                    
                    for p in parsed:
                        normalized = self._normalize_finding(p, "sqlmap")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"sqlmap failed for {target}: {e}")
            
            # Execute arjun for parameter discovery
            try:
                arjun_threads = "20" if agg == "default" else "50" if agg == "high" else "100"
                arjun_timeout = 180 if agg == "default" else 300
                arjun_result = self.tool_runner.run(
                    "arjun",
                    ["-u", target, "-m", "GET", "-o", "/tmp/arjun.json", "-t", arjun_threads],
                    timeout=arjun_timeout
                )
                if arjun_result.get("success"):
                    try:
                        with open("/tmp/arjun.json", "r") as f:
                            arjun_output = f.read()
                        parsed = self.parser.parse("arjun", arjun_output)
                    except:
                        parsed = []
                    
                    for p in parsed:
                        normalized = self._normalize_finding(p, "arjun")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"arjun failed for {target}: {e}")
            
            # Execute jwt_tool for JWT vulnerability testing
            try:
                # First check if target has JWT tokens
                jwt_result = self.tool_runner.run(
                    "jwt_tool",
                    ["-u", target, "-C", "-d"],
                    timeout=120
                )
                if jwt_result.get("success"):
                    parsed = self.parser.parse("jwt_tool", jwt_result.get("stdout", ""))
                    for p in parsed:
                        normalized = self._normalize_finding(p, "jwt_tool")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"jwt_tool failed for {target}: {e}")
            
            # Execute commix for command injection testing
            try:
                commix_result = self.tool_runner.run(
                    "commix",
                    ["--url", target, "--batch", "--json-output", "/tmp/commix.json"],
                    timeout=300
                )
                if commix_result.get("success"):
                    try:
                        with open("/tmp/commix.json", "r") as f:
                            commix_output = f.read()
                        parsed = self.parser.parse("commix", commix_output)
                    except:
                        parsed = []
                    
                    for p in parsed:
                        normalized = self._normalize_finding(p, "commix")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"commix failed for {target}: {e}")
            
            # Execute testssl for TLS vulnerability scanning
            try:
                testssl_result = self.tool_runner.run(
                    "testssl",
                    ["--jsonfile", "/tmp/testssl.json", target],
                    timeout=300
                )
                if testssl_result.get("success"):
                    try:
                        with open("/tmp/testssl.json", "r") as f:
                            testssl_output = f.read()
                        parsed = self.parser.parse("testssl", testssl_output)
                    except:
                        parsed = []
                    
                    for p in parsed:
                        normalized = self._normalize_finding(p, "testssl")
                        if normalized:
                            all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"testssl failed for {target}: {e}")
            
            # Execute comprehensive web scanner
            try:
                web_scanner = WebScanner(timeout=10, rate_limit=0.1)
                web_findings = web_scanner.scan(target)
                
                for wf in web_findings:
                    # Map web scanner findings to normalized format
                    normalized = self._normalize_finding(wf, "web_scanner")
                    if normalized:
                        all_findings.append(normalized)
            except Exception as e:
                logger.warning(f"WebScanner failed for {target}: {e}")
        
        return all_findings
    
    def run_analysis(self, job: Dict) -> Dict:
        """
        Execute analysis phase
        
        Args:
            job: Job dictionary
        
        Returns:
            Analysis results
        """
        self._check_timeout()
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="analyze"
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="analyze",
            engagement_id=self.engagement_id
        )
        
        # Get findings from database
        findings = []
        if self.finding_repo:
            try:
                findings = self.finding_repo.get_findings_by_engagement(self.engagement_id)
                findings = [f.to_dict() for f in findings]
            except Exception as e:
                logger.warning(f"Failed to load findings: {e}")
        
        # Import Intelligence Engine and Loop Budget
        from intelligence_engine import IntelligenceEngine
        from loop_budget_manager import LoopBudgetManager
        from snapshot_manager import SnapshotManager
        
        # Create snapshot
        db_conn = os.getenv("DATABASE_URL")
        snapshot_mgr = SnapshotManager(db_conn)
        snapshot = snapshot_mgr.create_snapshot(self.engagement_id)
        
        # Initialize budget manager
        budget_config = job.get("budget", {})
        budget_mgr = LoopBudgetManager(self.engagement_id, budget_config)
        
        # Evaluate with Intelligence Engine
        engine = IntelligenceEngine(db_conn)
        snapshot["findings"] = findings
        snapshot["loop_budget"] = budget_mgr.to_dict()
        
        evaluation = engine.evaluate(snapshot)
        
        # Extract actions
        actions = evaluation.get("actions", [])
        
        # Check budget for continuation
        next_state = "reporting"
        for action in actions:
            can_continue, reason = budget_mgr.can_continue(action)
            if can_continue:
                budget_mgr.consume(action)
                next_state = "recon"  # Loop back for more scanning
            else:
                logger.info(f"Budget exhausted: {reason}")
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="analyzing",
            to_state=next_state,
            reason="Analysis completed" if next_state == "reporting" else "Additional targets discovered"
        )
        
        return {
            "phase": "analyze",
            "status": "completed",
            "actions": actions,
            "scored_findings": evaluation.get("scored_findings", []),
            "reasoning": evaluation.get("reasoning", ""),
            "next_state": next_state,
            "trace_id": get_trace_id(),
        }
    
    def run_reporting(self, job: Dict) -> Dict:
        """
        Execute reporting phase
        
        Args:
            job: Job dictionary
            
        Returns:
            Reporting results
        """
        self._check_timeout()
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="report"
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="report",
            engagement_id=self.engagement_id
        )
        
        # Generate final report
        # Transition to complete state
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="reporting",
            to_state="complete",
            reason="Reporting completed"
        )
        
        return {
            "phase": "report",
            "status": "completed",
            "next_state": "complete",
            "trace_id": get_trace_id(),
        }
    
    def _check_timeout(self):
        """
        Check if hard timeout has been exceeded
        
        Raises:
            EngagementTimeoutError: If timeout exceeded
        """
        if self.start_time is None:
            return
        
        elapsed = time.time() - self.start_time
        
        if elapsed > self.HARD_TIMEOUT_SECONDS:
            # Log timeout event
            self._log_timeout_event(elapsed)
            
            raise EngagementTimeoutError(
                f"Engagement {self.engagement_id} exceeded hard timeout "
                f"of {self.HARD_TIMEOUT_SECONDS} seconds (elapsed: {elapsed:.2f}s)"
            )
    
    def _log_timeout_event(self, elapsed_seconds: float):
        """
        Log timeout event to execution logs
        
        Args:
            elapsed_seconds: Elapsed time in seconds
        """
        # Log timeout event
        logger.warning(
            f"Engagement {self.engagement_id} exceeded hard timeout. "
            f"Elapsed: {elapsed_seconds:.2f}s, Limit: {self.HARD_TIMEOUT_SECONDS}s"
        )
    
    def get_elapsed_time(self) -> float:
        """
        Get elapsed time since start
        
        Returns:
            Elapsed time in seconds
        """
        if self.start_time is None:
            return 0.0
        
        return time.time() - self.start_time
    
    def get_remaining_time(self) -> float:
        """
        Get remaining time before timeout
        
        Returns:
            Remaining time in seconds
        """
        elapsed = self.get_elapsed_time()
        return max(0.0, self.HARD_TIMEOUT_SECONDS - elapsed)
    
    def run_repo_scan(self, job: Dict) -> Dict:
        """
        Execute repository scanning phase (Semgrep static analysis)
        
        Args:
            job: Job dictionary with repo_url
            
        Returns:
            Repo scan results
        """
        self._check_timeout()
        
        repo_url = job.get("repo_url")
        
        # Publish job started event
        self.ws_publisher.publish_job_started(
            engagement_id=self.engagement_id,
            job_type="repo_scan",
            target=repo_url
        )
        
        # Log job started
        self.logger.log_job_started(
            job_type="repo_scan",
            engagement_id=self.engagement_id,
            target=repo_url
        )
        
        # Execute repository scan
        repo_aggressiveness = job.get("aggressiveness", "default")
        findings = self._execute_repo_scan(repo_url, job.get("budget", {}), repo_aggressiveness)
        
        # Save findings to database
        findings_count = len(findings)
        if self.finding_repo and findings:
            try:
                for finding in findings:
                    self.finding_repo.create_finding(
                        engagement_id=self.engagement_id,
                        finding_type=finding.get("type", "UNKNOWN"),
                        severity=finding.get("severity", "INFO"),
                        endpoint=finding.get("endpoint", ""),
                        evidence=finding.get("evidence", {}),
                        confidence=finding.get("confidence", 0.5),
                        source_tool=finding.get("tool", "semgrep"),
                    )
            except Exception as e:
                logger.error(f"Failed to save repo findings: {e}")
        
        # Publish state transition event
        self.ws_publisher.publish_state_transition(
            engagement_id=self.engagement_id,
            from_state="created",
            to_state="awaiting_approval",
            reason="Repository scan completed"
        )
        
        return {
            "phase": "repo_scan",
            "status": "completed",
            "findings_count": findings_count,
            "next_state": "awaiting_approval",
            "trace_id": get_trace_id(),
        }
    
    def _execute_repo_scan(self, repo_url: str, budget: Dict, aggressiveness: str = "default") -> List[Dict]:
        """
        Execute Semgrep scan on a repository using vibe-security-ultra custom rules.
        
        Args:
            repo_url: GitHub/GitLab repo URL
            budget: Budget configuration
            aggressiveness: Scan aggressiveness level (default, high, extreme)
            
        Returns:
            List of code vulnerability findings
        """
        import tempfile
        import shutil
        import subprocess
        import os
        
        all_findings = []
        agg = aggressiveness or "default"
        
        # Get path to custom semgrep rules
        rules_dir = os.path.join(os.path.dirname(__file__), "semgrep_rules")
        
        temp_dir = tempfile.mkdtemp(prefix="argus_repo_scan_")
        
        # Aggressiveness config for repo scans
        clone_depth = ["--depth", "1"] if agg == "default" else ["--depth", "1"] if agg == "high" else []
        semgrep_timeout = 300 if agg == "default" else 600 if agg == "high" else 1200
        custom_rule_limit = 3 if agg == "default" else 6 if agg == "high" else 999
        include_pro_rules = agg == "extreme"
        
        try:
            # Clone repository
            clone_cmd = ["git", "clone"] + clone_depth + [repo_url, temp_dir]
            clone_timeout = 120 if agg in ("default", "high") else 300
            clone_result = subprocess.run(
                clone_cmd,
                capture_output=True,
                text=True,
                timeout=clone_timeout
            )
            
            if clone_result.returncode != 0:
                logger.warning(f"Failed to clone repo {repo_url}: {clone_result.stderr}")
                return []
            
            self.ws_publisher.publish_scanner_activity(
                engagement_id=self.engagement_id,
                tool_name="git",
                activity=f"Cloned repository ({'shallow' if clone_depth else 'full'} clone)",
                status="completed",
                target=repo_url,
            )
            
            # Build custom rules list from available directories
            rule_subdirs = [
                "secrets",
                "auth",
                "injection",
                "xss",
                "ssrf",
                "csrf",
                "auto",
                "business-logic",
                "deserialization",
            ]
            custom_configs = []
            for subdir in rule_subdirs:
                config_dir = os.path.join(rules_dir, subdir)
                if os.path.isdir(config_dir):
                    custom_configs.append(config_dir)
            
            # Run with auto rules as baseline
            self.ws_publisher.publish_scanner_activity(
                engagement_id=self.engagement_id,
                tool_name="semgrep",
                activity=f"Running Semgrep static analysis ({agg} mode)",
                status="started",
                target=repo_url,
            )
            
            semgrep_result = self.tool_runner.run(
                "semgrep",
                ["--json", "--config", "auto", temp_dir],
                timeout=semgrep_timeout
            )
            
            if semgrep_result.get("success"):
                parsed = self.parser.parse(
                    "semgrep", 
                    semgrep_result.get("stdout", "")
                )
                for p in parsed:
                    normalized = self._normalize_finding(p, "semgrep")
                    if normalized:
                        all_findings.append(normalized)
            else:
                logger.warning(f"Semgrep auto scan failed: {semgrep_result.get('stderr')}")
            
            # Also try custom rules if available
            if custom_configs:
                rules_used = 0
                for config in custom_configs:
                    if rules_used >= custom_rule_limit:
                        break
                    try:
                        semgrep_result = self.tool_runner.run(
                            "semgrep",
                            ["--json", "--config", config, temp_dir],
                            timeout=semgrep_timeout
                        )
                        if semgrep_result.get("success"):
                            parsed = self.parser.parse(
                                "semgrep", 
                                semgrep_result.get("stdout", "")
                            )
                            for p in parsed:
                                normalized = self._normalize_finding(p, "semgrep")
                                if normalized:
                                    # Avoid duplicates
                                    if not any(n.get("endpoint") == normalized.get("endpoint") for n in all_findings):
                                        all_findings.append(normalized)
                        rules_used += 1
                    except Exception as e:
                        logger.warning(f"Semgrep custom rules scan failed for {config}: {e}")
                
        except Exception as e:
            logger.warning(f"Repo scan failed: {e}")
        finally:
            # Cleanup temp directory
            try:
                shutil.rmtree(temp_dir)
            except:
                pass
        
        self.ws_publisher.publish_scanner_activity(
            engagement_id=self.engagement_id,
            tool_name="semgrep",
            activity=f"Repository scan complete — found {len(all_findings)} issues",
            status="completed",
            target=repo_url,
            items_found=len(all_findings),
        )
        
        return all_findings
