#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# run-standalone-tests.sh — Regression CI for standalone Python tests
#
# Runs all Python tests that do NOT require opentelemetry (which isn't always
# installed in CI/dev environments). Test files that transitively import the
# `tracing` module (which does `from opentelemetry import trace` at module
# level) will fail collection; this script excludes them explicitly.
#
# Usage:
#   ./scripts/run-standalone-tests.sh          # run all standalone tests
#   ./scripts/run-standalone-tests.sh -v       # verbose output
#   ./scripts/run-standalone-tests.sh --coverage  # with coverage report
#
# Maintenance: when a new test file is added and it doesn't require
# opentelemetry, just add it to the tests/ directory and it will be
# discovered automatically. If it DOES require opentelemetry, add its
# path (without the tests/ prefix) to EXCLUDED_FILES below.
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail

cd "$(dirname "$0")/../argus-workers"

# ── Test files that fail collection because they transitively import the
#    `tracing` module, which does `from opentelemetry import trace` at
#    module level.  When opentelemetry is not installed, these files raise
#    `ImportError` during collection and prevent the rest of the suite from
#    running.  Excluding them allows the ~250 independent test files to run.
#
#    This list was generated by running `pytest --collect-only` and recording
#    every file that raised an ImportError (or other collection error) not
#    related to the tests themselves.
# ──────────────────────────────────────────────────────────────────────────────

EXCLUDED_FILES=(
  # ── Tests that import celery_app → tracing → opentelemetry ──
  test_bugbounty.py
  test_celery_app.py
  test_dispatch_task.py
  test_maintenance.py
  test_replay.py
  test_report.py
  test_scheduled.py
  test_task_bugbounty.py
  test_task_maintenance.py
  test_task_posture.py
  test_task_replay.py
  test_task_scheduled.py
  test_task_security.py
  test_tasks_recon.py
  test_tasks_repo_scan.py
  test_tasks_scan.py

  # ── Tests that import parsers.parser → tracing → opentelemetry ──
  test_analyze.py
  test_diff.py
  test_new_parsers.py
  test_nmap_parser.py
  test_normalizer_utils.py
  test_orchestrator.py
  test_orchestrator_pkg_recon.py
  test_orchestrator_pkg_repo_scan.py
  test_orchestrator_pkg_scan.py
  test_orchestrator_pkg_utils.py
  test_parser.py
  test_snapshot_service.py

  # ── Tests that import tool_runner → tracing → opentelemetry ──
  test_arjun_scanner.py
  test_ffuf_scanner.py
  test_port_scanner.py
  test_tool_arjun_scanner.py
  test_tool_context.py
  test_tool_ffuf_scanner.py
  test_tool_runner.py
  test_asset_discovery.py
  test_context.py
  test_budget_persistence_service.py

  # ── Tests that import tracing directly ──
  test_tracing.py

  # ── Tests that import intelligence_engine → llm_client → tracing ──
  test_intelligence_engine.py
  test_intelligence_engine_enhanced.py
  test_intelligence_service.py
  test_llm_batch_service.py
  test_llm_review.py

  # ── Tests that import mcp_bridge → tool_runner → tracing ──
  test_mcp_bridge.py

  # ── Collection errors from missing pytest markers ──
  test_fixture_comprehensive.py
  test_fixture_e2e_smoke.py
)

# ── Build --ignore flags ──
IGNORE_FLAGS=()
for file in "${EXCLUDED_FILES[@]}"; do
  IGNORE_FLAGS+=(--ignore "tests/${file}")
done

# ── Extra args passthrough (e.g. -v, --coverage, -x) ──
EXTRA_ARGS=("$@")

# ── Run pytest ──
echo "═══ Standalone Test Suite ═══"
echo "Excluded: ${#EXCLUDED_FILES[@]} test file(s) requiring opentelemetry"
echo ""

set -x
python -m pytest tests/ \
  "${IGNORE_FLAGS[@]}" \
  "${EXTRA_ARGS[@]}" \
  --tb=short \
  -ra \
  -p no:faulthandler
